### ISSUE TITLE
IEEE Open Access?

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#10]
Soweit ich mich erinnere war ja nur gesetzt, dass wir auf jeden Fall Open Access veröffentlichen wollen. Ist das richtig?

Haben wir uns eigentlich schon auf ein Journal geeinigt?

Falls ja, hätte ich eine Idee: Bei meiner Literaturrecherche ist mir aufgefallen, dass bereits einige Tools/Frameworks - allerdings in abgespeckter Form - über IEEE veröffentlicht wurden (Auswahl):

http://ieeexplore.ieee.org/document/6344667/
http://ieeexplore.ieee.org/document/5491276/
http://ieeexplore.ieee.org/document/4275718/
http://ieeexplore.ieee.org/document/6038913/
http://ieeexplore.ieee.org/document/4275374/

Allgemein kann man natürlich über das Geschäftsmodell großer Journals (Elsevier, IEEE) streiten. Allerdings ist der "Impactfaktor", gerade international, glaube ich nicht zu unterschätzen. Und wenn wir oemof nach außen kommunizieren wollen, benötigen wir Impact.

Zudem bietet IEEE auch die Möglichkeit Open Access zu veröffentlichen (http://open.ieee.org/pubchanges.html) und ich weiß, dass hierfür an unserer Hochschule Mittel in Form eines Open Access Publikationsfonds bereitstehen, die angeblich recht unproblematisch abgerufen werden können. Über die Höhe müsste man sich jedoch noch informiern. Evtl. könnte man ja auch in einem gemeinsamen Topf sammeln.

Wie steht ihr dem Thema (Open Access auf IEEE) gegenüber?

Beste Grüße
Cord

**Comment by simnh** [comment]
Wenn wir mittel haben, können wir das meinetwegen schon so machen. Ich glaube der 'Kampf' lässt sich dann auch woanders führen ;)

**Comment by simnh** [comment]
aber open access auf jeden fall...

**Comment by ckaldemeyer** [comment]
> Ich glaube der 'Kampf' lässt sich dann auch woanders führen ;)

Wir können ja als Ausgleich eine Auswahl von restriktiv veröffentlichten IEEE Papern zu OSS auf Scihub stellen ;)

**Comment by fraukewiese** [comment]
Hallo, hatten wir uns nicht schon auf das Aalborg Journal geeinigt, da komplett Open Access und so und kostenlos und Simon hatte ja auch schon nachgefragt ob wir es in LateX einreichen können?
WOllte da nur dran erinnern. Wenn jetzt gute Gründe dafür sprechen, doch was anderes zu nehmen vertrau ich EUch da das richtige auszusuchen. Diese Open Access Option bei Journals ist halst schon ne deutliche Spur schlechter vom Ansatz her. So ganz stimmig mit dem Inhalt des Papers ist es dann nicht. Aber wie gesagt, macht ma wie ihr meint, Hauptsache überhaupt Open Access, es erreicht viele Leute und wir können es in einem Format einreichen, das nicht viel Mehrarbeit macht.

**Comment by ckaldemeyer** [comment]
> Hallo, hatten wir uns nicht schon auf das Aalborg Journal geeinigt, da komplett Open Access und so und kostenlos und Simon hatte ja auch schon nachgefragt ob wir es in LateX einreichen können?
WOllte da nur dran erinnern. Wenn jetzt gute Gründe dafür sprechen, doch was anderes zu nehmen vertrau ich EUch da das richtige auszusuchen. Diese Open Access Option bei Journals ist halst schon ne deutliche Spur schlechter vom Ansatz her. So ganz stimmig mit dem Inhalt des Papers ist es dann nicht. 

Stimmt, das mit Aalborg hatte ich ganz vergessen! Wobei ich die LaTeX-Argumention ehrlich gesagt zweitranging finde. Wenn es daran scheitern sollte, übernehme ich notfalls die Umformatierung..

> Aber wie gesagt, macht ma wie ihr meint, Hauptsache überhaupt Open Access, es erreicht viele 
Leute und wir können es in einem Format einreichen, das nicht viel Mehrarbeit macht.

Gibt es irgendwo Statistiken darüber wieviele Leute das Aalborg-Journal lesen? Ich habe bisher ehrlich gesagt nur aus internen Kreisen (Treffen mit AAU,...) davon gehört. Zudem könnte ich mir vorstellen, dass der Artikel auch nicht unkritisch beäugt wird, da sie dort taktisch ja auf EnergyPlan setzen.

Ich glaube das was du angesprochen hast, ist gerade die eigentliche Debatte:

Open-Access-Kompromisslösung (gegen Zahlung) in bekanntem Journal mit hohem Impact vs. Real-Open-Access weniger bekanntem Journal mit nicht so hohem Impact

Beides hat natürlich Vor- und Nachteile. Ich wäre für diese Veröffentlichung eher für die erstere Variante, da wir, falls wir eine Finanzierung bekommen, mehr Impact haben. Wäre aber natürlich auch bei der zweiten Variante dabei, sofern die Gruppe sich dafür aussprechen sollte..

**Comment by simnh** [comment]
Bei aalborg können wir einfach erstmal als pdf einreichen...ich kann die diskussion nachvoll ziehen. aalborg können wir gerne versuchen, gibt es noch andere  journals, die du empfehlen kannst @fraukewiese?

**Comment by fraukewiese** [comment]
Energies von MDPI vll., Open Access und nciht zu teuer, weiss aber nicht obs inhaltlich passt, da muesstet ihr nochma schauen
oder PLOS ONE, supergut Open und auch bekannt, eben nicht themenspezifisch, aber ich finde das macht nichts.
Ich wuerde das mit dem impact nicht zu hoch haengen, ich glaub wenn es gut es wird es auch zitiert. und es ist auch schwieriger bei den ganz bekannten reinzukommen.

**Comment by ckaldemeyer** [comment]
> Ich wuerde das mit dem impact nicht zu hoch haengen, ich glaub wenn es gut es wird es auch zitiert. und es ist auch schwieriger bei den ganz bekannten reinzukommen.

Ich würde am liebsten auch auf ein Full-OA Journal gehen und glaube auch, dass es natürlich zitiert wird wenn es gut ist. Ich habe nur das Gefühl, dass das Auffinden vieler Papers manchmal nicht so einfach ist und Standard-Anlaufstellen sind nunmal IEEE und Sciencedirect. Aber wie gesagt, können wir gerne gemeinsam entscheiden ;)

**Comment by simnh** [comment]
Closed in favor of #19  where we decided PLOS ONE
