### ISSUE TITLE
Results, Discussion for MDPI 

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#100]
* Diskutieren wir noch die Methodik? Wenn ja wo (extra discussion section)
* Nehmen wir die vorgestellte Methodik noch explizit in die Conclusion auf und auch ggf. in die Results? 
Über diese 2-Teilung müssen wir noch entscheiden. 

Mein Vorschlag:
Wir sollten finden ich beides tun. Für die Analyse des frameworks ist alles eigentlich da und auch in vernünftigen Kapiteln. Für die Gesamtbetrachtung der Methodik fast nichts. Das sollte aber finde ich noch sein, auch schon wegen des Titles. Die Frage ist wo wir das machen...Vielleicht dann doch eine Discussion section die das methodische vorgehen diskutiert...das sollte dann noch in die conclusion aufgenommen werden, dafür etwas vom inhalt zurückschrauben..versteht ihr was ich meine ? was denkt ihr?

**Comment by ckaldemeyer** [comment]
> Diskutieren wir noch die Methodik? Wenn ja wo (extra discussion section)

Würde ich auf jeden Fall auch sagen! Entweder zwei Sections in der Discussion (Methodik, Case Study) oder einfach ohne Sections arbeiten. Letzteres reicht wahrscheinlich aus..

> Nehmen wir die vorgestellte Methodik noch explizit in die Conclusion auf und auch ggf. in die Results?
> Über diese 2-Teilung müssen wir noch entscheiden.

Ich wäre dafür die Methodik mit in die Conclusion aufzunehmen, da das Wichtigste aus der Discussion ja ohnehin in der Conclusion auftaucht (~"Komprimierte Form der Discussion, in der nichts Neues mehr dazu kommt.").

> Mein Vorschlag:
> Wir sollten finden ich beides tun. Für die Analyse des frameworks ist alles eigentlich da und auch in vernünftigen Kapiteln. Für die Gesamtbetrachtung der Methodik fast nichts. Das sollte aber finde ich noch sein, auch schon wegen des Titles. Die Frage ist wo wir das machen...Vielleicht dann doch eine Discussion section die das methodische vorgehen diskutiert...das sollte dann noch in die conclusion aufgenommen werden, dafür etwas vom inhalt zurückschrauben..versteht ihr was ich meine ? was denkt ihr?

Ich glaube, dass was ich geschrieben habe geht doch in die Richtung, oder? Habe dich zumindest auch so verstanden ;)

**Comment by ckaldemeyer** [comment]
Ich habe mir gerade nochmal das Paper angeschaut und auch einen Blick in andere Paper geworfen, die ich gut finde/fand.

Da wir schon viel "diskutierenden Charakter" in der Case Study (Challenges/Properties) haben, ist es glaube ich in diesem Fall aufgedoppelt nochmal ausführlich zu diskutieren. Ich würde glaube ich, so wie es jetzt ist, einfach "Discussion and conclusion" in einem Abwasch machen.

Dort kann man dann zuerst die Ergebnisse der Case Study (Challenges, Properties, Evaluation) diskutieren und anschließend die die allgemeine Methodik kritisch analysieren (shortcomings, ...). Zudem könnte man noch einen Ausblick und weitere Anschlussarbeiten aufzeigen. Das wäre m. E. ziemlich sauber

**Comment by simnh** [comment]
sehe ich auch so...

**Comment by gplssm** [comment]
Ich plädiere auch dafür die Discussion und Coclusions in einem Kapitel zu machen. Dort würde ich allerdings nicht mehr diskutieren welche Challenges warum adressiert sind, sondern dies nur nochmal zusammenfassen. Alle Argumentationen, Diskussion und Einordnung der adressierten Challenges würde ich in Kapitel 3 (Case Study) vornehmen. Ggf. könnte Sec. 3.3 noch etwas hinsichtlich der Darstellung adressierter Challenges ausgeweitet werden (wobei dies eigentlich eine Wdh. der Inhalten der vorherigen Section ist).

Ich schlage folgende Struktur für Kap. 4 vor (und integriere dabei existierenden Text mit links):

* Abriss des Inhalts des Papers
* Erklärung und [Begründung/Rechtfertigung der Methodik](https://github.com/simnh/addressing_challenges_oemof/blob/085f50ba96d14f66094c2e145796a6b43673bffb/addressing_energy_system_modelling_challenges.tex#L1102-#L1125)
* [Shortcomings](https://github.com/simnh/addressing_challenges_oemof/blob/085f50ba96d14f66094c2e145796a6b43673bffb/addressing_energy_system_modelling_challenges.tex#L1128-#L1141)
* Ergebnisse der Case Study _oemof_
* Weitere Verwendung dieser Methodik und Verbesserungspotenzial
* Empfehlungen für ModelliererInnen (hinsichtlich Challenges)
* Evtl. einen Ausblick (z.B. Entwicklungen in _oemof_)

Das ganze würde ich ohne Zwischenüberschriften als ein Kapitel schreiben. So hätten wir eine Struktur an der wir uns langhageln können und finden (hoffentlich) ein abrundendes Kapitel für das Paper.

**Comment by simnh** [comment]
Finde ich grundsätzlich gut, bei den Ergebenissen der Case-Study bin ich nicht so sicher, ich fand es eigentlich gut, beispiel Ergebnisse rauszugreifen um damit die methodik zu untermauern..aber dafür kann das Ergebnis auch kurz vorher zusammengefasst werden...klären wir morgen

**Comment by gplssm** [comment]
Strukturvorschlag aus Telko

* Abriss des Inhalts des Papers: 3-4 Sätze, qualitative Methode zur Evaluation von Frameworks, Modellen, Anwendung auf oemof, ...
 * Erklärung und Begründung/Rechtfertigung der Methodik: "Warum die Methode?", "Was macht die Methode?" 
* Ergebnisse der Case Study oemof (Kurz nennen, nicht diskutieren da diskussion schon vorher stattgefunden hat)   
* Shortcomings (Troz schwächen gut andwendbar -> haben wir gemacht Überleitung zu ergebnissen)
* Benefits
* Possible improvements & weitere Verwendung dieser Methodik
* Empfehlungen für ModelliererInnen (hinsichtlich Challenges)/Lessons learned/Fazit: Die Methodik generiert neue Erkenntnisse, da sie die Aus der Synthese von Challenges und Characteristics aufzeigt, wo im Bereich der Energiesystemmodellierung Handlungs-/Forschungsbedarf besteht (strukturierte Analyse)

Idee von Cord: Conclusion als Mini-Kapitel (<1/2 Seite)

**Comment by gplssm** [comment]
Ich habe nun mal einen Aufschlag für das Discussion und Conclusions Kapitel gemacht. Dabei habe ich die obige Struktur angewendet, nur der Punkt "Benefits" taucht nicht auf, weil es für mich an der Stelle keinen Sinn ergab. Außerdem habe ich die Conclusions nicht in ein extra Kapitel gepackt.
Insgesamt dürft ihr das befreit krtisieren und zerreißen. Auf gute Sprache habe ich keinen Fokus gelegt. Versucht euch davon nicht rausbringen zu lassen.

Ich würde euch (insb. @ckaldemeyer) nun bitten das gegenzulesen und Änderungswünsche direkt umzusetzen, telefonisch zu diskutieren oder erstmal aufzuschreiben. Dabei wäre folgende Priorität sinnvoll: Struktur cheken, inhaltliche Lücken beheben, Ausdruck/Sprache verbessern.

[Einem Abschnitt](https://github.com/simnh/addressing_challenges_oemof/blob/3138e0cbca3a4f0e82c5e5c21fd52eac6a055377/addressing_energy_system_modelling_challenges.tex#L1163-#L1169) fehlt noch das Fleisch (bzw. Tofu). @ckaldemeyer könntest du hier nachfüttern?
Weiterhin wäre es super, wenn du die [Zusammenfassung der Ergebnisse](https://github.com/simnh/addressing_challenges_oemof/blob/3138e0cbca3a4f0e82c5e5c21fd52eac6a055377/addressing_energy_system_modelling_challenges.tex#L1125-#L1148) noch einmal kritisch beäugen könntest.

**Comment by simnh** [comment]
super danke guido, finde es ist ne gute Basis, damit sollten wir nun bald endlich fertig sein...

**Comment by ckaldemeyer** [comment]
Memo: auf Zeiten (Present tense, past tense, past perfect) achten und durchgängig anwenden

**Comment by ckaldemeyer** [comment]
Memo: emph und Naming glatt ziehen (z. B. oemof immer hervorgehoben oder nicht)

**Comment by ckaldemeyer** [comment]
> Ich habe nun mal einen Aufschlag für das Discussion und Conclusions Kapitel gemacht. Dabei habe ich die obige Struktur angewendet, nur der Punkt "Benefits" taucht nicht auf, weil es für mich an der Stelle keinen Sinn ergab. Außerdem habe ich die Conclusions nicht in ein extra Kapitel gepackt.
> Insgesamt dürft ihr das befreit krtisieren und zerreißen. Auf gute Sprache habe ich keinen Fokus gelegt. Versucht euch davon nicht rausbringen zu lassen.
> 
> Ich würde euch (insb. @ckaldemeyer) nun bitten das gegenzulesen und Änderungswünsche direkt umzusetzen, telefonisch zu diskutieren oder erstmal aufzuschreiben. Dabei wäre folgende Priorität sinnvoll: Struktur cheken, inhaltliche Lücken beheben, Ausdruck/Sprache verbessern.

Danke @gplssm für deine Arbeit!

Zusammenfassung für euch beide:

Nach Absprache mit @gplssm habe ich jetzt den diskutierenden Teil aus dem Case Study Summary in die Discussion gezogen. So ist die Trennung zwischen beschreibendem Teil (Evaluation Summary) und kritischem, bewertenden Teil (Discussion) m. E. klarer. Zudem habe ich ein Conclusion Kapitel angelegt, um allgemeine Aussagen bzw. Schlussfolgerungen sowie zusammenfassende Teile aus der Diskussion herauszulösen. Zudem habe ich dann noch versucht die neue Struktur von den Paragraphengewichten und den Texten (relativ viel Geschleife) aufeinander anzupassen.

Das Ergebnis sehr ihr im letzten Commit. Weiter bin ich nicht gekommen aber ich denke, auf der Basis kann man das zusammen mit den Zeiten (Past tense, ...), dem allgemeinen Stil (We, Passiv, ...) sowie dem Wording (Analysis, Evaluation, Approach, Methodology, oemof emph,...) einmal glattziehen.

Wir nähern uns dem Ziel! Ich mache jetzt aber erstmal Wochenende ;-)

> Einem Abschnitt fehlt noch das Fleisch (bzw. Tofu). @ckaldemeyer könntest du hier nachfüttern?
> Weiterhin wäre es super, wenn du die Zusammenfassung der Ergebnisse noch einmal kritisch beäugen könntest.

Bis auf einen Satz (=der von dir) habe ich das jetzt so gelassen und finde es auch o.k. Sonst ufert es noch aus und der Fokus ist ja auch wieder ein wenig mehr vom Ansatz in die Symbiose aus diesem und der Case Study gewandert bzw. auf das, was man daraus an Erkenntnissen ableiten kann.

Bis denne!

**Comment by simnh** [comment]
Die discussion und conclusion echt ganz gut so, allerdings noch folgende punkte, die ich änder würde, wenn das für euch ok ist: 

- Versuchen die oemof ergebniss zusammenfassung zu kürzen, die finde ich schon sehr lang...aber muss nicht (was denkt ihr ja/nein/kann)
- bisschen guckn, das nicht zu viele trivialitäten genannt werden. ich denke das z.b. uncertaitnty addressiert werden muss wird überall zu hauf genannt, ich finde (wie schon gesagt) die aspekte interessanter die auf der meat ebene liegen und den rest würde ich eher kurz halten. 

Fehlt für euch noch was?

**Comment by simnh** [comment]
achso danke euch beiden, echt super arbeit!!!

**Comment by ckaldemeyer** [comment]
Wenn wir inhaltlich d'accord sind, würde ich vorschlagen, dass wir uns nochmal in folgenden Punkten einig werden und das Paper dahingehen prüfen:

* Erzählform: we, passiv, ...
* Naming: approach/method, model/model generator/ framework/, usw.
* ?

Im gleichen Zuge des letzten Schliffs, könnte man nochmal Formulierungen, etc. prüfen.

Dann würde ich nochmal anregen das Paper an eine Person aus dem Modellierungskosmos zu geben, die nicht zu stark involviert ist und kritisch (aber nicht zu kritisch) gegenliest und prüft, ob der rote Faden klar wird bzw. wo noch Unklarheiten auftauchen. Als KandidatInnen fallen mir da spontan z. B. Marion, Martin S., Birgit oder Caro ein.

Dann kann Frauke ja ein letztes Mal drüberlesen und wir schicken es ab. Was meint ihr dazu?

**Comment by simnh** [comment]
jo, also ich bin für 'we'...

ansonsten können wir das so machen..

**Comment by ckaldemeyer** [comment]
> jo, also ich bin für 'we'...

Da kann ich wie gesagt auch mitgehen.

> ansonsten können wir das so machen..

Sag doch einfach Bescheid wenn du durch bist!

**Comment by ckaldemeyer** [comment]
> ich muss gestehen, jetzt wo ich nochmal detaillierte drauf geguckt habe finde ich die aspekte von der oemof conclusion sollten doch drin bleiben. Eigentlich fand ich sie innerhalb der case-study nicht schlecht verortet...aber wenn wir es so lassen ist es auch ok.

Finde sie da auch besser. Deswegen habe ich sie auch verschoben :-)

> Dann wäre noch ein vorschlag, doch unterkapitel innerhalb der discussion einzuführen, um die struktur klarer hervorzuheben (wir können ja keine absätze mit leerzeile machen bei mdpi, so wie ich das verstanden habe).
> 
> Irgendwie sowas wie:
> 
> Discussion of casestudy results.
> Discussion of methodology
> und dann haben wir ja eine extra conclusion...

Darüber hatte ich auch schon nachgedacht aber habe mich dann am Fr. doch spontan für das "Sandwich" aus Absätzen entschieden. Finde die Idee eigentlich auch besser mit Überschriften (Methodology, Case Study) zu arbeiten, da es bestimmt anders wirkt.

> wobei hier auch der erste teil der discussion schon conclusion charakter hat...(so war es ja mal gedacht, als dis. and conc) ...

Ich würde erstmal nur an die Klarheit der Discussion denken, unabhängig von der Conclusion. Die kann man dann ja anpassen..

**Comment by ckaldemeyer** [comment]
Ist ja eigentlich auch nur ein Schieben von Absätzen, das mit den Überschriften.

**Comment by simnh** [comment]
Also sorry, ich komme immer wieder zu dem punkt, dass ich denke, die discussion of case study results sollte innerhalb der case study liegen, weil sie meiner meinung nach eher zu der evaluation als zu dem gesamten paper gehört...falls ihr das nicht so seht wäre ich über einen vorschlag dankbar, wie wir das unter einen hut kriegen. bzw. vielleicht findet ihr das ja auch gut so? dann können wir es so lassen...

**Comment by ckaldemeyer** [comment]
> Also sorry, ich komme immer wieder zu dem punkt, dass ich denke, die discussion of case study results sollte innerhalb der case study liegen, weil sie meiner meinung nach eher zu der evaluation als zu dem gesamten paper gehört...falls ihr das nicht so seht wäre ich über einen vorschlag dankbar, wie wir das unter einen hut kriegen. bzw. vielleicht findet ihr das ja auch gut so? dann können wir es so lassen...

Ich finde, dass beides argumentierbar ist aber mir gefällt die Diskussion der Case Study results in der Discussion aus folgenden Gründen immer noch besser:

* Der Charakter ist klar diskutierend
* Die Abfolge innerhalb der Discussion (Kurzintro, Methodik, Case Study) ist die gleiche bzw. kann die gleiche sein wie in der Struktur des Papers (Intro, Methodik, Case Study)
* Die Diskussion wird nur mit dem methodischen Teil im Vergleich zum Gesamtumfang des Papers zu dünn
* In der Abbildung "evaluation approach" heisst der dritte Schritt "Summary" und nicht "Discussion", daher ist m. E. die Tabelle sehr passend zu "Summary"

Bist du jetzt vorerst durch mit deinen Änderungen? Sonst kann ich auch nochmal drüberschauen..

**Comment by ckaldemeyer** [comment]
> Bist du jetzt vorerst durch mit deinen Änderungen? Sonst kann ich auch nochmal drüberschauen..

Ich schaue jetzt nochmal rüber und melde mich dann hier

**Comment by ckaldemeyer** [comment]
> Also sorry, ich komme immer wieder zu dem punkt, dass ich denke, die discussion of case study results sollte innerhalb der case study liegen, weil sie meiner meinung nach eher zu der evaluation als zu dem gesamten paper gehört...falls ihr das nicht so seht wäre ich über einen vorschlag dankbar, wie wir das unter einen hut kriegen. bzw. vielleicht findet ihr das ja auch gut so? dann können wir es so lassen...
> Ich finde, dass beides argumentierbar ist aber mir gefällt die Diskussion der Case Study results in der Discussion aus folgenden Gründen immer noch besser:
> 
> Der Charakter ist klar diskutierend
> Die Abfolge innerhalb der Discussion (Kurzintro, Methodik, Case Study) ist die gleiche bzw. kann die gleiche sein wie in der Struktur des Papers (Intro, Methodik, Case Study)
> Die Diskussion wird nur mit dem methodischen Teil im Vergleich zum Gesamtumfang des Papers zu dünn
> In der Abbildung "evaluation approach" heisst der dritte Schritt "Summary" und nicht "Discussion", daher ist m. E. die Tabelle sehr passend zu "Summary"
> Bist du jetzt vorerst durch mit deinen Änderungen? Sonst kann ich auch nochmal drüberschauen..

Vielleicht ist das jetzt auch schon -zumindest inhaltlich und strukturell- der Punkt "Es wird nicht mehr besser/schlechter, sondern nur noch anders."?

Dann könnten wir uns nochmal auf die Sprache, Terminologie und das was noch nicht fertig ist stürzen und das Ding an eine Person geben.

**Comment by ckaldemeyer** [comment]
Bin durch und habe Folgendes erledigt:

* Challenge addressment wieder in case study geschoben
* Discussion neu strukturiert. Absätze: Intro, Advantages, Disadvantages, General Issues, Recommendations

Insgesamt wäre es m. E. vom Umfang schön mit der Discussion auf mindestens eine (knappe) Seite zu kommen.

Vielleicht könnte man die Absätze noch ein wenig ausführlicher gestalten. Mir fällt aber gerade nix ein und ich muss los bzw. was anderes machen..
