### ISSUE TITLE
Methodology überarbeiten

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#102]
* Herleitung, warum so etwas wichtig ist
* Generisch anfangen (könnte man auch auf andere Modellarten übertragen..)
* Dann spezifisch werden (Energiesystemchallenges und Modelle/Frameworks)

**Comment by simnh** [comment]
Ich weiß nicht ob die Herleitung in der Methodik so gut aufgebhoben ist...das wäre ja eher aus einem Status Quo abzuleiten der sich vielleicht in der Introduction unterbringen lässt...

das mit dem generischen finde ich gut...da kann man sicherlich auch nochmal gucken was es so in anderen bereichen gibt an evaluation...

@ckaldemeyer wir sollten uns vielleicht einmal zusammen setzen? dann alle offenen fragen zu ende diskutieren und ich könnte dass dann machen. nächste woche hätte ich dafür komplett zeit...

**Comment by ckaldemeyer** [comment]
> Ich weiß nicht ob die Herleitung in der Methodik so gut aufgebhoben ist...das wäre ja eher aus einem Status Quo abzuleiten der sich vielleicht in der Introduction unterbringen lässt...

Da haste Recht.

> das mit dem generischen finde ich gut...da kann man sicherlich auch nochmal gucken was es so in anderen bereichen gibt an evaluation...
> 
> @ckaldemeyer wir sollten uns vielleicht einmal zusammen setzen? dann alle offenen fragen zu ende diskutieren und ich könnte dass dann machen. nächste woche hätte ich dafür komplett zeit...

Ist vielleicht das Einfachste! Einfach wieder einen Tag Writeathlon?

**Comment by simnh** [comment]
jo

**Comment by ckaldemeyer** [comment]
> jo

Dienstag und Mittwoch sind schlecht bei mir. Sonst sollte es eigentlich passen. Vielleicht am Donnerstag?
