### ISSUE TITLE
Finalize paper

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#103]
* [x] Methodik überarbeiten (erst generisch dann energiespezifisch) + Literatur #92  #102 
     Literatur für status quo, Scenario Fact sheet, RegMex, Connlly Review
     (new section name: nicht methodik des papers sondern neue methodik vorgestellt) @simnh
* [x] Revise Introduction etwas kürzen (linked to methodik) #101 @simnh
* [x] Tabelle oemof property/characteristics überarbeiten @ckaldemeyer 
* [x] Result table improvement @ckaldemeyer 
* [x] Discussion of methodology / Include methodology in Discussion and conclusion: 1. Methodology, 2. Case Study results @ckaldemeyer, @simnh
* [x] Re-write abstract @ckaldemeyer
* [x] Rename case study in figure 1 to setup / parametrisation @ckaldemeyer 
* [x] Chapter "Case Study": Little introduction..
* [ ] Evaluation: Check if further references exist e.g. "an energy system can be connected to THE graph" should be formulated  "an energy system can be connected to A graph" or the graph theory should be explained if it is mentioned the first time
* [x] Get naming straight in text: challenges, aspects, properties, characteristics @ckaldemeyer

**Comment by ckaldemeyer** [comment]
Habe das Abstract komplett neu geschrieben. Kannst ja mal drüberschauen!

**Comment by simnh** [comment]
Moin, also ich weiß nicht, wo wir gerade diskustieren, ich habe jetzt nochmal drauf geguckt. Den Abstract finde ich gut und bei der Einleitung würde ich noch einen Satz hinzufügen, dass es bis jetzt kaum evaluation approaches für frameworks gitb und dann auf den ersten Teil der Methodology verweisen....oder wir ziehen das mit in die introduction


Ansonsten würde ich das Morgen nochmal drucken und durchgehen und dann Frauke geben...
