### ISSUE TITLE
Sammlung kleiner Diskussionspunkte von Guido

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#104]
_dies ist eine Sammelliste von Guido mit Punkten, die nicht direkt umgesetzt wurden. Punkte mit "@" können von der jeweiligen Person gerne direkt bearbeitet werden_

- [x] [Den Satz verstehe ich nicht](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L115-#L117) @ckaldemeyer können wir im Zweifelsfall telefonisch besprechen
- [x] Können wir weitere Keywords hinzufügen? Ich würde vorschlagen: open source, open data (oder einfach open science), oemof @simnh 
- [x] [Satz überarbeiten, evtl. Mittelteil rauslöschen](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L167-#L170)
- [x] [Ich verstehe an der Stelle nicht was mit "lines" gemeint ist](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L194)
- [x] [Referenz ETSAP fehlt, bitte einfügen wer weiß was damit gemeint ist](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L195) @simnh 
- [x] Bibtex-Eintrag RegMex2017 fehlt @simnh 
- [ ] [Wollen wir wirklich in Futur schreiben? Ich würde konsequent Präsens verwenden.](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L296-#L326)
- [x] [Der Satz wurde nicht zuende gebracht und ich weiß nicht was da hin muss](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L774-#L775) @simnh 
- [x] [Kann dieser TODO-Hinweis gelöscht werden?](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L780) @simnh 
- [ ] Kapitel-/Sektionsüberschriften von 3.3, 3.3.1 und 4 anpassen. Guidos Vorschlag:
* 3.3: Results and discussion
* 3.3.1: Subüberschrift löschen, da einziges Element dieser Gliederungsebene
* 4: Reflecting the evaluation approach
@simnh wir können das gerne telefonisch klären
- [ ] [Die Aussage des Satzes wird so nicht deutlich](https://github.com/simnh/addressing_challenges_oemof/blob/fc1c2f3de420ac13fead39c9ba7d321176d5581b/addressing_energy_system_modelling_challenges.tex#L1052-#L1054)
- [x] Wollen wir keine Acknowledgments section haben?

Tasks für Guido
* Abstract überarbeiten
* Introduction überarbeiten
* Discussion überarbeiten

**Comment by simnh** [comment]
> Ich verstehe an der Stelle nicht was mit "lines" gemeint ist

http://idioms.thefreedictionary.com/along+the+lines+of

Bin nicht sicher, ob es vielleicht umgangsprachlich ist, daher kann es gerne umformuliert werden...aber als deutsche-sprachler kann ich es gut lesen ;)

**Comment by simnh** [comment]
>  Wollen wir keine Acknowledgments section haben?

Ich brauche keinen...oder wer/was fällt euch ein?

**Comment by ckaldemeyer** [comment]
>> Wollen wir keine Acknowledgments section haben?
> Ich brauche keinen...oder wer/was fällt euch ein?

Wollen wir vielleicht alle ursprünglich Beteiligten bzw. Leute aus dem oemof-Kosmos (RLI/ZNES), die irgendwo mal mitgewirkt haben nennen? Fände ich ganz nett.

Und evtl. nochmal openmod als Inputgeber für interessante Diskussionen und Kontakte..

**Comment by gplssm** [comment]
Sehr gute Anregung, Cord! Ich schlage vor

* den früheren Autoren des Papers zu danken und deren Mitwirkung zu Erwähnen
* den oemof-Entwicklern zu danken
* weiteren Personen zu danken, wenn diese bspw. gute Punkte in einer Diskussion gebracht haben. Ich habe da niemanden, aber vielleicht hattet ihr ja solche Treffen z.B. auf dem OpenMod Treffen

**Comment by ckaldemeyer** [comment]
> Sehr gute Anregung, Cord! Ich schlage vor
> 
> den früheren Autoren des Papers zu danken und deren Mitwirkung zu Erwähnen
> den oemof-Entwicklern zu danken
> weiteren Personen zu danken, wenn diese bspw. gute Punkte in einer Diskussion gebracht haben. Ich habe da niemanden, aber vielleicht hattet ihr ja solche Treffen z.B. auf dem OpenMod Treffen

Wir sollten nur nicht durchblicken lassen, dass es im im Prinzip nur "Reste" des alten Papers waren, aus denen wir das neue generiert haben. Kommt bestimmt nicht so gut beim Reviewer :)

**Comment by ckaldemeyer** [comment]
> Sehr gute Anregung, Cord! Ich schlage vor
> 
> den früheren Autoren des Papers zu danken und deren Mitwirkung zu Erwähnen
> den oemof-Entwicklern zu danken
> weiteren Personen zu danken, wenn diese bspw. gute Punkte in einer Diskussion gebracht haben. Ich habe da niemanden, aber vielleicht hattet ihr ja solche Treffen z.B. auf dem OpenMod Treffen

Ansonsten :+1:
