### ISSUE TITLE
Kapiteleinleitungen

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#105]
Derzeit haben wir nur unter "Case Study" einen Absatz als Kapiteleinleitung aber nicht im Rahmen der Methodik bzw. in der Discussion.

Entweder sollten alle raus oder überall eine aufgenommen werden - auf jeden Fall sollte es einheitlich gelöst werden.

**Comment by simnh** [comment]
sehe ich nicht so, denn das ist das case study kapitel, was über 80 % des Papers ausmacht...
