### ISSUE TITLE
Storyline

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#106]
Wie diskutiert mit Simon:

* Vielzahl an existierenden Modellen, etc.
* Wenig strukturierte Herangehensweisen zur Bewertung dieser hinsichtlich der Eignung für verschiedene zukünftige Herausforderungen
* Wir schlagen eine (einfache) qualitative und strukturierte Methode vor
* Gleichzeitig wenden wir diese auf ein Framework der second generation hinsichtlich zukünftiger Challenges an
* Damit zeigen wir, dass die Methodik allgemein anwendbar und übertragbar ist
* Zudem können empfehlungen für andere Frameworks der second generation abgeleitet werden

**Comment by simnh** [comment]
agree! in der Introduction und Abstract sowie discussion fehlt noch der letzete bullet point (sonst ist meiner meinung nach die storyline so vorhanden)

**Comment by ckaldemeyer** [comment]
> Damit zeigen wir, dass die Methodik allgemein anwendbar und übertragbar ist
> in der Introduction und Abstract sowie discussion fehlt noch der vorletzte bullet point (sonst ist meiner meinung nach die storyline so vorhanden)

Ich lese gleich nochmal drüber und füge das dann hinzu.
