### ISSUE TITLE
add acknoledgments 

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#107]
like discussud in #104 

Wenn es jemand machen will, ich habe da kein bedürfnis, denn wir haben meiner meinung nach das paper so gut wie alleinge gestaltet....

**Comment by ckaldemeyer** [comment]
> like discussud in #104
> 
> Wenn es jemand machen will, ich habe da kein bedürfnis, denn wir haben meiner meinung nach das paper so gut wie alleinge gestaltet....

Sehe ich mittlerweile auch so.

**Comment by ckaldemeyer** [comment]
Wobei...ich mache da einfach mal was. Schadet ja nicht ;)

**Comment by ckaldemeyer** [comment]
> Wobei...ich mache da einfach mal was. Schadet ja nicht ;)

Habe mich dagegen entschieden. Eigentlich kam da jetzt auch keine wesentliche Hilfe.
