### ISSUE TITLE
Figures: mapping = cartesian product / some pre-selection

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#108]
We should clarify that challenges(aspects) and properties(characteristics) are either mapped completely (meaning that many arrows to not occur) or that there's a pre-section.

@simnh, @gplssm  : Which way would you prefer? I would prefer the first.

It's then just changing arrows in the figure..

**Comment by simnh** [comment]
wie du meinst...go with the first one..

**Comment by gplssm** [comment]
Ich verstehe den Kontext der Frage leider zu wenig. Bin aber gerade im Büro und erreichbar...

**Comment by ckaldemeyer** [comment]
> Ich verstehe den Kontext der Frage leider zu wenig. Bin aber gerade im Büro und erreichbar...

Figure 1. Schematic illustration of the methodology: Each characteristic of a framework property is
evaluated relating to its contribution to the aspects of each energy system modelling challenge.

Hier sollten wir eigentlich von jeder Characteristic zu jedem Aspect Pfeile machen, oder?

Zumindest war meinem Prof. das aufgefallen, als ich das Paper hier kurz vorgestellt habe und wenn wir das als formalen approach verkaufen sollte das visuelle auch zum textuellen/mathematischen passen.

**Comment by simnh** [comment]
ja richtig, wobei die Darstellung ja auch nur die 'grünen' pfeile darstellen kann, sonst wirds ggf. so unübersihtlich

**Comment by ckaldemeyer** [comment]
> ja richtig, wobei die Darstellung ja auch nur die 'grünen' pfeile darstellen kann, sonst wirds ggf. so unübersihtlich

Ich würde dann noch die "o" Pfeile aufnehmen und in der Beschriftung sagen, dass unaddressed Pfeile "-" nicht aufgenommen sind.

**Comment by gplssm** [comment]
Danke!

Wenn man also den Text 1:1 in Fig. 1 "2. Evaluation" wiedergeben will, müsst man das kartesische Produkt einzeichnen, das ist wahr. Würde m.E. den Leser aber nicht wirklich weiterbringen, da es unübersichtlich wird.
Ich habe "2. Evaluation" von Fig. 1 bisher so interpretiert, dass die Pfeile exemplarisch zeigen wo Zusammenhänge einzelner characteristics und aspects bestehen und welchen Zusammenhang sie haben (+/o/-). Es werden also die nicht relevanten nicht dargestellt.

**Comment by ckaldemeyer** [comment]
> Danke!
> 
> Wenn man also den Text 1:1 in Fig. 1 "2. Evaluation" wiedergeben will, müsst man das kartesische Produkt einzeichnen, das ist wahr. Würde m.E. den Leser aber nicht wirklich weiterbringen, da es unübersichtlich wird.
> Ich habe "2. Evaluation" von Fig. 1 bisher so interpretiert, dass die Pfeile exemplarisch zeigen wo Zusammenhänge einzelner characteristics und aspects bestehen und welchen Zusammenhang sie haben (+/o/-). Es werden also die nicht relevanten nicht dargestellt.

Also wärst du mit



> Ich würde dann noch die "o" Pfeile aufnehmen und in der Beschriftung sagen, dass unaddressed Pfeile "-" nicht aufgenommen sind.

d`accord?

Und dann kann ich im Text ja nochmal das kartesische Produkt fallen lassen und auf die Figure eingehen..

**Comment by simnh** [comment]
ich finde alle was du machst gut :)

**Comment by simnh** [comment]
![matrix](https://user-images.githubusercontent.com/2633688/28459137-916b50f4-6e0c-11e7-9562-308ad204e452.png)

**Comment by simnh** [comment]
für  @gplssm

**Comment by ckaldemeyer** [comment]
> ich finde alle was du machst gut :)

Schön ;D

Dann warte ich nochmal auf Guidos Meinung und ab geht's. 

@simnh : Die Matrix war echt ne super Idee. Das bringt nochmal einen richtigen Mehrwert!
