### ISSUE TITLE
get uncertainty definition straight

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#109]
epistemic / aleatory is inside tables, though in the text it is often referred to as structural / variability uncertainty

**Comment by gplssm** [comment]
Do you have a preference for epistemic / aleatory or structural / variability uncertainty?

**Comment by simnh** [comment]
I just realized, that we have structural uncertainty as a subscategory of epistemic ...maiy the same holds for aleatory..I woul prefer to stick to the definition we make at the beginning in the section that you mainly wrote (5 different types of uncertainty). Maybe you can just keep it in mind for you final proof reading..

**Comment by gplssm** [comment]
Yep, I will do this when I read through it.
