### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#112]
There should be no figures included in the tex.
I now commented them out in the tex.
Captions have to be put to the end of the tex-file.
Find out how to hand in the figures.

**Comment by simnh** [comment]
Ich hab das noch nie so ricthig verstanden, aber anscheinend wird es ja so gemacht...

**Comment by fraukewiese** [comment]
Aus den submission guidelines. Dann geht es fuer uns wohl nur drum die ans Ende zu packen und nicht includefigure zu nutzen.

Note that figures must be submitted as separate image files, not as part of the submitted manuscript file. For more information, see 'Preparing figures' below.

Additional information for TeX/LaTeX users

Please use BioMed Central's TeX template and BibTeX stylefile if you use TeX format. Submit your references using either a bib or bbl file. When submitting TeX submissions, please submit both your TeX file and your bib/bbl file as manuscript files. Please also convert your TeX file into a PDF (please do not use a DIV file) and submit this PDF as a supplementary file with the name 'Reference PDF'. This PDF will be used by our production team as a reference point to check the layout of the article as the author intended. Please also note that all figures must be coded at the end of the TeX file and not inline.

When preparing figures, please follow the formatting instructions below.

https://energsustainsoc.springeropen.com/submission-guidelines/preparing-your-manuscript/original-articles#preparing+figures

**Comment by fraukewiese** [comment]
Ok, habs nochmal gelesen und die figures einfach wieder an Ort und Stelle im Manuskript einkommentiert. Denke das geht. includegraphichs ist durch zwei Zeilen im .tex ausser Kraft gesetzt, so dass sie nicht angezeigt werden, so wollen die das auch haben. Dann muessen die Grafiken nur noch entsprechend ihrer Reihenfolge durchnummeriert mit eingereicht werden.
