### ISSUE TITLE
Literature: Reproducability/Quality Control in Scientific Computing

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#12]
Moin zusammen,

hat jemand noch Literatur zu dem o. g. Thema? Ich würde das gerne im Paper unter "Contribution" verorten.

Ausgangspunkt wäre der folgende Artikel mit den entsprechenden Quellen:

http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745

Grüße
Cord

**Comment by fraukewiese** [comment]
Cao, K.-K., Cebulla, F., Gómez Vilchez, J. J., Mousavi, B., & Prehofer, S. (n.d.). Raising awareness in model-based energy scenario studies—a transparency checklist. https://doi.org/10.1186/s13705-016-0090-z

**Comment by ckaldemeyer** [comment]
Danke!
