### ISSUE TITLE
Uniform figure style

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#15]
I would offer myself to format all figures in a uniform style. So far, there are only figures in the "Framework" chapter.

Do you have any further figures that should be integrated?

Otherwise I would start today or tomorrow.

**Comment by simnh** [comment]
i do not think there are.

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by ckaldemeyer** [comment]
Wasn fürn English/Deutsch-Wechsel hier... ;-)

**Comment by ckaldemeyer** [comment]
Habe die Figures mal neu mit yEd erstellt bzw. bestehende angepasst. Ist noch nicht perfekt aber schon mal besser. Schiebe/ändern können wir ja immer noch..
