### ISSUE TITLE
Pre peer-review

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#18]
General  comments (specific ones in the text as \todo[inline] )
- Pfenninger 2014 is cited a bit too often
- streamlining oemof namespace, oemof core: - between (in text) or not (in figure)?

Ideas for suggested Reviewers
- Hans Ravn
- Tom Brown

**Comment by gplssm** [comment]
General questions/comments
* Shall we introduce an abbreviation for energy system model(s), such as ESM?
* As _modern realities_ is used as a term, it should be introduce more clear. Make a clear definition for that term
* I would like to restructure the text [over here](https://github.com/simnh/addressing_challenges_oemof/blob/6398f4b4c3d59460bf02457d3b212a4c3cc253fb/introduction.tex#L13-#L24) in co-work with someone else

Suggested Reviewers
* Mark Howells
* David Kleinhans

**Comment by simnh** [comment]
I think abbrv. is a good and I like the idea of a clearer definiton, that s definitely missing. The question is: Where? if used inside the introduction, we could do it there (not really me favorite one). Or we can just describe the background inside the introduction without using the term and introduce the term somewhere later, to use it throughout the paper.

**Comment by fraukewiese** [comment]
energy system models: short description of what we mean by that in the introduction is good, I think. 

GENERAL COMMENTS TO CONTRIBUTION SECTION:
- suggestion to make four subsections for "Open", "Collaborative", the structural stuff and "overview" to better carve out what contributes to what
- put the general points of what contributes to what that is written at the beginning of the chapter at the moment to the "overview" subsection
- I really like the idea of the  table and would build on that idea. The wording in chapter contribution of the section challenges should be exactly the same like in the section contribution. Also in this table. I would put the table in section discussion.
- Instead in section contribution I would suggest an additional figure I drafted here: https://github.com/simnh/addressing_challenges_oemof/blob/master/figures/suggested_figure_for_contributions.png This figure works out which characteristic contributes in which way to which challenge. This also helps us to structure it in the text and to draw conclusions I think. The figure is absolutely not complete, a first draft to find out if you agree that is is a good idea @gplssm @simnh @gnn @ckaldemeyer @uvchik 
- Uncertainty is broadly described in section challenges, that should refer to more on that in section contribution. If we do not have more to say about it, it could be shortened a bit in section challenges as well.
- with what software do you generate the figures? Dia?

GENERAL COMMENTS TO CONCLUSION SECTION:
- we need more substance here as this is what readers read if they further read after the abstract
- I would suggest to first conclude oemofs contribution, not repeating the stuff but shortly summarize: (1) that open lays the foundations (and many models are going that way, maybe including the reference to which transparency checklists oemof fulfills as suggested by cord (2)collaborative software dev. contributes further ... more and more tools that make it possible (e.g. github), maybe some more stuff from your experience, what you recongnized you learn during this collab. work, github, but still barriers (project oriented research, financing structure)... (3) structural ... is foundation for challenges in context with modelling techniques.
- Then the table adapted to the same wording as used in challenges section and the potential figure
- Then elaborate on that the structural stuff lays the foundation for challenges in context with modelling techiniques . framework is good. but: some (what?) has to be solved on the application-level.
- There are challenges left, not possible to solve neither on framework nor on application level. On research organization level maybe, societal level...
- What future research should do. come back a little from the big picture to oemof

**Comment by simnh** [comment]
@fraukewiese  thanks for the feedback, I totally I agree with everything you mentioned. Guido and you both mentioned all points I had in mind but I was not able to write down. 
I like  the idea with the table at the beginning and at the end and an additional figure (need to see if we use both, but the figure seems to be promising) . For graphics we use yed (*.graphml files I think) 

I also think first of all we should gather all comments (with proposals for new structures) and after that start restructuring etc. 

Regarding the contribution section I think it indeed makes sense if other developers add value and structure as they might have an 'new' perspective...

**Comment by simnh** [comment]
@ckaldemeyer Maybe we can push the yed-files as well, so that these can be edited?

**Comment by ckaldemeyer** [comment]
> with what software do you generate the figures? Dia?

For the figures I used yEd. Another program which I quite like is LibreOffice Draw.

> @ckaldemeyer Maybe we can push the yed-files as well, so that these can be edited?

Yep, I'll have a look and push them.

**Comment by ckaldemeyer** [comment]
I have pushed the yEd files on the master!

**Comment by simnh** [comment]
Thanks a lot for the feedback. We will transfer everything thats listed here to the tex file and close this issue. The next steps will be structured as follows: 

- Go through all comments and adapt the text 
- If the comment is a larger one, we will create an issue and link it inside the pdf. Discussions regarding these comments / problems will take place at these issues. (please not mail) 
- We will keep the comments using color codes (green resolved / yellow proposed but not sure / check and red: no idea at all)  
- Goal is to hand in end of this year
- We will summarize the new issues under a milestone 'final-draft'
