### ISSUE TITLE
Journal Choice

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#19]
Based on the discussions in https://github.com/oemof/organisation/issues/7 and https://github.com/simnh/addressing_challenges_oemof/issues/10

From my point of view, there are three options left if we are not aiming at Elsevier or Springer (which would be my preference, see also http://www.leopoldina.org/fileadmin/redaktion/Publikationen/Allianz/2016_12_02_DEAL.pdf why):

**Energies**
http://www.mdpi.com/journal/energies/about
pro: fully open access / fast: a first decision provided to authors approximately 31 days after submission / peer-reviewed / energy-relalted
contra: don't now what kind of reputation the journal has, topic of the journal fitting to energy but maybe not especially to modeling tools.
costs: 1400 CHF

**International Journal of Sustainable Energy Planing and Management**
https://journals.aau.dk/index.php/sepm/about/submissions#authorGuidelines
pro: open access / no fee / peer-review / 5000-8000 words
contra: AAU is promoting EnergyPlan and they already questioned oemof at our 100%RE conference, no latex style for handing in (maybe on request) / long review time?

**PLOS ONE**
http://journals.plos.org/plosone/s/journal-information
PLOS ONE features reports of original research from all disciplines within science and medicine. By not excluding research on the basis of subject area, PLOS ONE facilitates the discovery of connections between research whether within or between disciplines.
Submissions describing methods, software, databases, or other tools We consider submissions describing methods, software, databases, or other tools if they follow the appropriate reporting guidelines. See the submission guidelines for more information.
pro: one of the very first open access / fully open access / latex / good policies
contra: $1,495 USD (http://journals.plos.org/plosone/s/publication-fees) / not energy-realated

**IEEE**
http://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=60 (oder Power Transactions, o. ä.)
http://open.ieee.org/pubchanges.html
pro: high impact factor / international peer group / open access / peer-review / latex-hand-in mit fertigem template
contra: fees ($1,750-$1,950), old-fashioned and only partly open journal

I know that some people from our wind institute have published in **Energies**..

**Comment by ckaldemeyer** [comment]
My vote:

1. IEEE
2. Energies
3. PLOS ONE
4. AAU Journal

I just think that our chances in Aalborg might not be the best since we are providing a competetive product from their point of view. And I think that IEEE e.g. on power transactions has a high impact which I would appreciate for this first publication!

**Comment by simnh** [comment]
Thanks for the input. Generally, Í like your order, but I think regarding the content PLOS ONE would fit even  better than IEEE. My favorite is PLOS ONE, although I like the fast argument very much. If you think Energies category 'Energy Policy/ Sustainable Energy Systems' could fit this would also be ok for me. I think assume what is clear is that neither Elsevier, Springer nor AAU will be it...(from discussions etc with authors)

**Comment by cswh** [comment]
My favourite would be PLOS ONE as well. Especially because they take as well "Studies reporting negative results" and "replication studies". Which is not the case for us, but should be supported in general within the scientific publishing community.

Another positive systematic thing is "Data Availability: Authors must follow standards and practice for data deposition in publicly available resources including those created for gene sequences, microarray expression, structural studies, and similar kinds of data. Failure to comply with community standards may result in rejection." Should be standard everywhere as well.

Perhaps this even has the potential to become a standard journal of a kind for our research group. And perhaps the "Open Access" Money from HS, EUF and SH could somehow be connected to an [Institutional Account](https://www.plos.org/institutional-account-participants) in the long term... I have a dream... Go Oldenberg...

**Comment by fraukewiese** [comment]
Plos One is certainly the one most fitting to our general science understanding.

So lets get to the practical issues.
Good: "Manuscripts can be any length. There are no restrictions on word count, number of figures, or amount of supporting information. We encourage you to present and discuss your findings concisely."
http://journals.plos.org/plosone/s/submission-guidelines

But we have to use their latex template:
http://journals.plos.org/plosone/s/latex

Did or could someone check how much work that would be?

**Comment by cswh** [comment]
It is not too complicated to use their template and adhere to their latex guidelines. I could take care of that.

**Comment by gplssm** [comment]
I haven't looked for any other suitable journal. My list of preference based on proposed Journals

1. PLOS ONE
2. AAU Journal
...

But PLOS ONE requires funding for OA publication to be available. If I remember right, @simnh has some money!?

I would support adapting the manuscript to a new template. I could do this along with formatting work on references.

**Comment by simnh** [comment]
As I am at the university now, its a little more complicated, but I can ask for funding (we have a budget for open access at the EUF, I will do so on monday). Funding from the EUF would also exclude IEEE, as money will only be given for 'real' open access journals.

**Comment by ckaldemeyer** [comment]
I have asked for funding at HS FL, too and we will see what they say.

Basically, I think PLOS ONE is a good choice in terms of our principles!

**Comment by simnh** [comment]
We go with PLOS ONE, hope we get financing from our departments....
