### ISSUE TITLE
Emerging approaches as subsection or existing approaches as own section

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#2]
Nachdem ich die Section "susceptibility to bugs and bias" gefüllt hab, ist mir aufgefallen, dass es "emerging approaches (subsection chapter 2) und die eigene section "existing approaches".
Frage mich ob das so soll oder ob da ein Unterschied ist? Wer schreibt das?

**Comment by fraukewiese** [comment]
äh, muss ich @simnh @uvchik @gplssm @cswh @ckaldemeyer schreiben damit ihr mitbekommt, dass es hier ein neues issue gibt oder passiert das automatisch?

**Comment by simnh** [comment]
Wir haben uns dafür entschieden erst state of start challenges und dann state of art approaches in zwei aufeinanderfolgenden sections zu schreiben. 
section 3 (jetzt irgendwie noch nicht 3) bezieht sich damit auf die in section 2 beschriebenen challenges

@cswh  schreibt section 3 bis zum 21.07. 

du kannst ja deinen geschriebenen block einfach bei section 3 einfügen dann kann clemens das bei sich einbinden...

**Comment by fraukewiese** [comment]
prima, hab ich gemacht

**Comment by ckaldemeyer** [comment]
@fraukewiese : du brauchst uns nicht extra zu highlighten ;)

**Comment by uvchik** [comment]
> äh, muss ich @simnh @uvchik @gplssm @cswh @ckaldemeyer schreiben

Nein, musst Du nicht. Generell bekommen das alle, die "Watcher" sind. Und wer kein "Watcher" ist, muss halt regelmäßig gucken, ob sich was getan hat, aber das ist ja dann die eigene Entscheidung.

**Comment by cswh** [comment]
Wegen anderer ToDos und Krankheit kriege ich meine Section erst einen Tag später am 22.07. fertig.

**Comment by fraukewiese** [comment]
Beim Lesen der 2.6 Existing Approaches fiel mir auf dass man die auch gut in die 5 Punke davor eingliedern könnte. Falls sich das jeweils zuordnen lässt zu ner challenge. Falls die existing approaches eher übergreifend sind, vll. doch den Unterpunkt belassen.

**Comment by simnh** [comment]
Existing approaches are listed in section 2 with the challenges....
