### ISSUE TITLE
Document a "best practice way" to work together on the source code

### ISSUE THREAD

**Issue by cswh** [simnh/addressing_challenges_oemof#20]
* should that go into the wiki? or should be documented here within the issue? @ authors: feel free to add opinion

**Comment by ckaldemeyer** [comment]
wiki

**Comment by cswh** [comment]
see [[How we work here...]].
For changes/updates/new tings please reopen this issue again.

**Comment by simnh** [comment]
I think this has been documented quite well by @cswh

**Comment by uvchik** [comment]
Ist es eigentlich okay auf deutsch zu schreiben, denn im Gegensatz zu oemof muss dieser Prozess ja nicht für externe nachvollziehbar sein. Oder seht ihr das anders?

**Comment by simnh** [comment]
ja klar
