### ISSUE TITLE
Uncertainties in abstract

### ISSUE THREAD

**Issue by cswh** [simnh/addressing_challenges_oemof#24]
\todo[inline,color=red]{Frauke: Ist damit Uncertainties concerning the future 
gemeint oder in der Future von oemof, da es noch nicht implementiert ist?}

**Comment by cswh** [comment]
Ich glaube eher uncertainties concerning the future. Das könnte man noch klarer rausstellen.

**Comment by simnh** [comment]
ja es geht um die challenge uncertainty und nicht um die ungewissheit von oemof.  I assigned @fraukewiese

**Comment by simnh** [comment]
We revised the abstract. we may add few lines (~50 word) if something is missing. Please review!

**Comment by fraukewiese** [comment]
Sounds good what you changed.
Nevertheless, when conclusions are written, abstract should be read again and evtl. changed, see issue
https://github.com/simnh/addressing_challenges_oemof/issues/54
