### ISSUE TITLE
Subsection Complexity

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#29]
The complexity subsection needs to be revised. There exist some ideas. 
```
\todo[backgroundcolor=blue!40!white,inline,caption={}]{Guido: Ich würde auch 
dieses Unterkapitel in der Struktur noch schärfen wollen. Wir könnten es wie 
folgt aufbauen
\begin{itemize}
 \item Woher kommt die Komplexität?
 \item Welchen Dimensionen der Komplexität begnenen wir? (vielleicht auch in 
Einheit mit vorherigem Punkt)
 \item Die Erstellung der Eingangsdatensätze beinhaltet komplexe Berechnungen 
(wir könnten dies auch als eine Dimension der Komplexität ansehen!?)
 \item Zielkonflikt: Präzision der Modellierung vs. einfaches, übersichtliches 
Modell
 \item weitere Abhängigkeiten zu anderen ''Challenges``
\end{itemize}
Das meiste ist schon im Text vorhanden. Es muss nur teilweise umstrukturiert 
und angepasst werden
}
```

**Comment by simnh** [comment]
I gave it it shot but I am not really happy. It could need some citetations and I realised that we should talk at some point about bottom up / top down models and how they are modelled / solved.

**Comment by simnh** [comment]
I realised there are no approaches mentioned inside the complexity section. We should do that: 
Ideas:
- linking models, iteratively solving of models 
- various techniques of aggregation of time (I could provide literature) 
- ...?

**Comment by fraukewiese** [comment]
I would suggest to move the main amount of words and references about human dimension to the interdisciplinarity section, away from the complexity section and just mention it in complexity and refer to interdisciplinarity, ok?
@simnh @ckaldemeyer 
also refers to: #31 and #46

**Comment by simnh** [comment]
Feel free. If you move the paragraph about agent based modelling due to liberalisation of markets you need to make the point why this is interdisciplinary ('agents' != humans) and this can be a classical economic approach..

**Comment by fraukewiese** [comment]
Very good hint that agent-based can be classical economic but also more social science related. So I separated the explanation and the references between complexity and interdisciplinarity. So I added a paragraph according to your todo in the subsection and added literature but did not change anything else in this subsection

**Comment by simnh** [comment]
II think this (sub)section can be reviewed.

**Comment by ckaldemeyer** [comment]
#27  (post on complexity)
