### ISSUE TITLE
figure to illustrate the oemof structure

### ISSUE THREAD

**Issue by uvchik** [simnh/addressing_challenges_oemof#3]
Hier sing zwei Ansätze, um die oemof-Struktur zu veranschaulichen. Der erste versucht ein Modellbild und die mögliche Nutzung der Bibliotheke zu vereinen, der zweite basiert auf dem bekannten Bild aus der Dokumentation. Seht die beiden Bilder als Gedankenanstöße. Manchmal hilft es ja etwas vor Augen zu haben um Ideen zu entwickeln oder zu verwerfen.

Der Code ist hier, falls jemand Lust hat die Ideen graphisch weiter zu entwicklen. Kommentare sind aber auch gewünscht. https://gist.github.com/uvchik/709f70a8b1d14b3f51e57f5437661c04

![oemof_paper](https://cloud.githubusercontent.com/assets/4760584/16803430/9996ba10-4906-11e6-875a-4c20ce688b6c.png)

**Comment by fraukewiese** [comment]
Schick. Veranschaulichungen find ich bei Modellen immer ziemlich essentiell fürs Verständnis.

_Fragen/Anmermkungen Erster Ansatz:_
- Warum geht der demand-Pfeil nicht in electricity rein?
- Was bedeutet die Ellipse "electricity"?
- Bedeutet "creating a network" network im Stromnetz-Sinn oder eine Verbindung von pvlib, demandlib, solph usw.?
- Fürs Allgemein-Verständnis wäre es super noch zu erklären, was die verschiedenen Formen und Farben bedeuten, also z.B. sind alle gelben eckigen Teile Einspeiseprofile-Bibliotheken?

_Zweiter Ansatz:_
- Der macht find ich schön den modularen Aufbau klar
- Warum gibt es immer genau drei blaue Felder? Das wirkt so als müsste es pro Funktionalität drei geben, ist ja aber gar nicht so, oder?
- Warum ist solph unter creating and energy system und simulation/optimisation (nur so ne Interesse-Frage)

**Comment by simnh** [comment]
Die Grafiken sind ja ohnehin nur ein Draft, aber ich denke es ist wichtig zumindest das Grundkonzept von oemof (das genauer im oemof-core-paper beschrieben ist) als erstes kurz zu erläutern, (Node, Bus-components-network), dann erübrigen sich die ersten Fragen (auch für andere Leser). 

Die zweite Grafik finde ich ansich auch gut, aber ich denke es macht nicht viel Sinn viele 'leere' Kästen dort darzustellen. Da muss es eine andere Möglichkeit geben....

**Comment by ckaldemeyer** [comment]
> Die zweite Grafik finde ich ansich auch gut, aber ich denke es macht nicht viel Sinn viele 'leere' Kästen dort darzustellen. Da muss es eine andere Möglichkeit geben....

Sehe ich auch so. Erste Idee: Einfach weglassen?

Bei der ersten Abbildung würde ich alles Spezifische (ENTSO-E, ...) weglassen.

Allgemein würde ich eher mit Formen und weniger mit Farben arbeiten. Beide Abbildungen würden ohne Farbe immer noch die gleiche Information enthalten. Evtl. wären Grautöne auch ein Kompromiss..

Ist aber auch Geschmackssache ;-)
