### ISSUE TITLE
General challenges structure

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#32]
We need to fix the challenges structure and all 'sub-challenges'. This concerns basically everthing including the table of challgens at the beginning and the end as well as the figure in contribution section

**Comment by simnh** [comment]
Ok I am having a hard time here, but I ll try to formulate my ideas: 

- Rename usability to result communication (as thats what is in there) 
- Add Food Water Energy Nexus to complexity and somehow relsolve the conflict that this is also linked to interdisciplinarity (s #31 ). Or come up with a other structure
- Scientific standards will entail: 
   - 

-  Resolve problem of broad definition of uncertainty that basically links to all other challenges

**Comment by ckaldemeyer** [comment]
> Do we want to add Usability from a user perspective?

Yes, from my point of view. I think this is quite important.

> Where would this go? (Usability and Applicability?)

Sounds good.

**Comment by ckaldemeyer** [comment]
> We then might come up with four major categories:
>
> Uncertainty (para, structural, linguistic etc)

Sounds good!

> Scientific standards (scientfic progress, value-laden ass., reproduci. / transpar)

Maybe "Scientific requirements" or "(Good) scientific practice"?

I don't know if "value-laden ass." fits well here. I would only put it in there if we can cite enough literature e.g. on standard scenario sheets (Cebulla), etc.. But atm. I don't know a better place for this either..

> Complexity (temporal, regional, input data, result analysis, sector coupling, interaction with new field (s. interdiscipli.) )

Sounds good!

> Interdisciplinary (human behaviour, energy food water )

Sounds good!

**Comment by cswh** [comment]
> > Scientific standards (scientfic progress, value-laden ass., reproduci. / transpar)
>
> Maybe "Scientific requirements" or "(Good) scientific practice"?
>
> I don't know if "value-laden ass." fits well here. I would only put it in there if we can cite enough literature e.g. on standard scenario sheets (Cebulla), etc.. But atm. I don't know a better place for this either..

I would rather stick with "Scientific standards" if we can connect it to a citable source. And we should include "scrutiny" as one major aspect.

**Comment by simnh** [comment]
we have the new structure. I makes sense to me...I will move this one to Done...
