### ISSUE TITLE
Section Framework (except contribution)

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#33]
The framework section has quit some comments, but it should be straight forward to implement these...
Maybe this is something for @gnn ?

**Comment by simnh** [comment]
@gnn  Will you do it?

**Comment by ckaldemeyer** [comment]
TODOs as discussed with @simnh :+1: 

* Figure with nodes
  * Extend by flows (weight of edge)?
  * Build container "EnergySystem" arround nodes
* UML class diagram
  * Find a way to describe the relations between the classes (arrows?)
  * Therefore, look up UML possibilities (Martin Glauer has some experience here)

**Comment by ckaldemeyer** [comment]
I would offer to extend the figure by the container as it is done quickly..

**Comment by ckaldemeyer** [comment]
I have now edited and scaled the figures.

**Comment by uvchik** [comment]
Das Bild (Fig.2) muss überarbeitet werden, denn das stimmt nicht. @gnn bist Du da gerade dran?

**Comment by uvchik** [comment]
@simnh wrote at issue [#43](https://github.com/simnh/addressing_challenges_oemof/issues/43#issuecomment-269471649)

> I think the info that authors and developers are not identical is good. We do not need to name developers but we might be a little more extensive on the acknowledge section:
>  * oemof is a collaborative project, builds on the contribution of many many developers
>  * maybe the main institutions: RLI, U Magdeburg, HS FL, Uni Fl ? (anything else?)
> 
> feel free :)

Ich glaube der Inhalt ist besser im Haupteile angesiedelt, denn ich finde das einen wichtigen Punkt. Ich würde dazu gerne einen Vorschlag machen, möchte Dir (@gnn) aber nicht in die Quere kommen. Wann wirst Du daran arbeiten?

**Comment by ckaldemeyer** [comment]
> Das Bild (Fig.2) muss überarbeitet werden, denn das stimmt nicht mehr. @gnn bist Du da gerade dran?

Nur zur Info: die *.graphml-Dateien liegen im Unterordner

Weil du letztes Mal scheinbar eine ältere Vorlage als Basis für deine Überarbeitungen genommen hast ;-)

**Comment by ckaldemeyer** [comment]
>> @simnh wrote at issue [#43](https://github.com/simnh/addressing_challenges_oemof/issues/43#issuecomment-269471649)

>> I think the info that authors and developers are not identical is good. We do not need to name developers but we might be a little more extensive on the acknowledge section:
>>  * oemof is a collaborative project, builds on the contribution of many many developers
>>  * maybe the main institutions: RLI, U Magdeburg, HS FL, Uni Fl ? (anything else?)
>> 
>> feel free :)

> Ich glaube der Inhalt ist besser im Haupteile angesiedelt, denn ich finde das einen wichtigen Punkt. 

:+1: 

Für mich wäre es aber kein ODER sondern eher ein UND, also kurz in den Acknowledgements, o.ä. und im Hauptteil.

**Comment by uvchik** [comment]
@gnn Du solltest den branch `oemof_community` mergen bevor Du anfängst den Absatz zu überarbeiten.

**Comment by gnn** [comment]
Ok, mach ich. Bin noch dran, braucht aber deutlich mehr Zeit als ich gedacht hab.

**Comment by simnh** [comment]
@gnn wenn du nochmal ggf. den master branch auch nochmal bei dir reinzumergen...solange du in deiner section bleibst is auch alles gut, ansonsten passiert gerade noch recht viel auf dem features/addressed_challenges branch

**Comment by simnh** [comment]
please merge features/open-challenges before introducing new stuff, as there have been made a lot changes ...

**Comment by gnn** [comment]
Still on it. Pushed a slight rewrite (along with one question) of the 'Philosophy and Delimitation' subsection onto [features/#33](https://github.com/simnh/addressing_challenges_oemof/tree/features/%2333). More to come.

**Comment by simnh** [comment]
just to be sure: The first paragraph has do be done from scratch I guess. I am not even sure that Philosophy and Delimitation needs to be one section. But when I worked on it, Philosophy was not so much, so I merged that with the Delimitation, which is important I think. We should answer following questions concerning the delimitation: 

1) What is oemof, what are its key characteristics ? 
2) What similar framework/model generators exist?
3) What's the difference between existing ones and our approach? 

But you will manage @gnn  ;)

**Comment by simnh** [comment]
Ok we will close this now, thanks for contribution @gnn !
