### ISSUE TITLE
Section Conclusion

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#35]
There needs to be more content. I guess the structure will follow easily. But we should avoid to discuss two much here if we discuss already in Section contribution (see also: #34 )

**Comment by simnh** [comment]
We may group smaller task under this epic

**Comment by simnh** [comment]
- briefly recap the challenges and where they come from...
- conclude oemofs contribution, not repeating the stuff but shortly summarize
 (1) that open lays the foundations (and many models are going that way, maybe including the reference to which transparency checklists oemof fulfills as suggested by cord 
(2)collaborative software dev.  contributes further ... more and more tools that make it possible (e.g.
github), maybe some more stuff  from your experience, what you recongnized you learn during this collab. work, github, but still  barriers (project oriented research, financing structure)... 
(3) structural... is foundation for challenges in context with modelling techniques.
- Add table from contribution
 - Then elaborate on that the structural stuff lays the foundation for
challenges in context with modelling techiniques . framework is good.
 but: some (what?) has to be solved on the application-level.
- There are challenges left, not possible to solve neither on framework
nor on application level.
 On research organization level maybe, societal level...
 -What future research should do. come back a little from the big picture
to oemof

**Comment by simnh** [comment]
We might want to Split Discussion and Conclusion or have a subsection Conclusion inside the discussion. As @cswh  mentioned in #34 , The 'contribution' section should only contain contributions, while the discussion section should contain possible future  stuff. In this way we will have strict distinction between contributions,  discussion and conclusions

**Comment by simnh** [comment]
We will split as proposed. Already done...This will be converted to taks now

**Comment by simnh** [comment]
Who wants to do it?

**Comment by fraukewiese** [comment]
What is above, I have suggested for the discussion https://github.com/simnh/addressing_challenges_oemof/issues/34 . I think conclusion should be really short. probably we should write discussion first and then put what is really concluding to conclusions or even just the table with 4 sentences

**Comment by simnh** [comment]
I agree, and I think we all do: short and precise with the table. Doing it after discussing with revising abstract #24

**Comment by ckaldemeyer** [comment]
> What is above, I have suggested for the discussion #34 . I think conclusion should be really short. 

I agree that it should be short!

> probably we should write discussion first and then put what is really concluding to conclusions or even just the table with 4 sentences

:+1:

**Comment by fraukewiese** [comment]
Points I came across in the paper, that could be worth mentioning in the conclusion (unsorted):
- the three characteristics open, collaborative, generic structure of oemof are - while not tackling all five mentioned challenges - essential for progress of all ESM
- Giving the framework conditions for necessary interdisciplinary energy system science is rather a societal challenge and cannot be solved by one framework or model
- There are barriers to collaborative ESM due to project and funding possibility oriented research

**Comment by simnh** [comment]
closed in favour of #68
