### ISSUE TITLE
Kontakt zum Journal aufnehmen

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#4]
Hallo,
ich würde gern schon mal Kontakt zum Journal aufnehmen, denn wenn es nicht geht in Latex den Artikel einzureichen, müssen wir uns was anderes suchen und haben dann vll. wieder andere Anforderungen an die Struktur des Artikels.

Hier also der Entwurf einer mail and den verantwortlichen Editor. Und zwei Fragen an Euch:
- Passt so vom Text?
- Soll ich das machen oder @simnh willst Du?

Ersma
frauke

poul@plan.aau.dk
Poul Alberg Østergaard

Dear Mr. Poul Alberg Østergaard,
 
we are currently working on a paper with the title "Addressing energy system modelling challenges: The
example of the Open Energy Modelling Framework - oemof".

Following a description of current energy system modelling challenges, the paper will describe how these could be tackled, with an emphasis on what an open and collaborative approach can contribute. It will be worked out which of the issues can be solved on the model level, which are more content-related (e.g. human factors, detail of models) and which could be only solved on the model framework level. In this context, the Open Energy Modeling Framework (oemof) will be described as an example for a framework that solves some of the challenges.

From our point of view, the content fits quite nicely to the International Journal of Sustainable Energy Planning and Management and we very much appreciate the open access policy of the journal.
Would the paper fit to the journal from your point of view?
Are there any temporal submission deadlines?

If yes, a question concerning the format.  As we are already working on a latex file, version-controlled with the help of git, which perfectly fits to the workflow of collaboratively writing the paper, we would very much appreciate if we could submit the paper as a latex file.
Would that be possible?

I look forward to your response, thanks in advance

**Comment by simnh** [comment]
Ja ich kann die Mail verschicken.  Würde ggf. noch ein zwei änderungen vornehmen. Setze euch CC
