### ISSUE TITLE
Check literature and add missing bibs

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#40]

**Comment by fraukewiese** [comment]
If the reference at the beginning of the sentence, shouldn't be there a \citet or \citep (I always forget which one is the right one) or something like that, so that the name appears in the text? Does it say something in the author guidlines of plos1 about that? @simnh @cswh

**Comment by simnh** [comment]
Not sure right now, just use the citation with cite for now, we will check at the end...

**Comment by cswh** [comment]
we can use `\citeauthor` from natbib for that.

**Comment by gplssm** [comment]
Nice hint to `\citeauthor`, but it does't work for me. I get
![image](https://cloud.githubusercontent.com/assets/8255114/21400723/cf0b7918-c7b1-11e6-8c5f-0a89ea2602f8.png)

when I do

```
\usepackage[numbers]{natbib} % in preamble

\citeauthor{Pfenninger2014}
```

Any clues, someone?

**Comment by simnh** [comment]
This seems not to be compatible with the PLOS ONE bibliography style. Please try to avoid author years citetation. If needed absolutely needed use explicit writing

**Comment by gplssm** [comment]
Ok, thanks for clarifying! I will use it sometimes when I find it appropriate ;)

**Comment by simnh** [comment]
@fraukewiese will you check the literature a final time?

**Comment by fraukewiese** [comment]
where can I find the reference list rules of PLOS1? @simnh @gplssm

**Comment by simnh** [comment]
PLOS1 has an own bst file which is already inside the repository. Later, we need to compile the bibliography and copy the bbl file content to the main.tex document...but do not bother with this.
I was rather thinking of typos, coherence, missing dois, etc....

**Comment by fraukewiese** [comment]
I rather meant: which order, title kursiv, journal abbreviated or rather not etc. ?

**Comment by gplssm** [comment]
@fraukewiese  Isn't this all defined by the .bst style file?

**Comment by fraukewiese** [comment]
There were some abbreviated journals for example. I now did all not abbreviated and included the http://dx.doi.org , so that these can be directly assesed by clicking. I also made no space between the pages, e.g 204-208 instead of 204 - 208.

I just got until reference 20. Can probably continue a bit in the afternoon (from 15:00 - 16:00), but feel free to continue if you want to have it done fast.

**Comment by gplssm** [comment]
Ok, now I got what you meant. Just say how far you went after the second session and I'll maybe continue tonight.

**Comment by fraukewiese** [comment]
got to [37] @Guido

**Comment by gplssm** [comment]
I continued until (incl.) [61].

I noticed DOI is not displayed with type _inproceedings_. Is this intended like this?

**Comment by gplssm** [comment]
I'm finished with all references. @fraukewiese could you please close this issue when you're fine with the result?

**Comment by fraukewiese** [comment]
Thanks a lot @gplssm 
I tried to do some more minor corrections (adding http://dx.doi.org... before the doi and deleting a double doi:doi: in some, but then there were some references missing although I had pulled before. So I skipped that as it is of minor importance before ruining the reference list again.
Just one thing, i would recommend to add: Could you add pages or doi or something, I did not find it online,  @simnh or @cswh or @gnn 
Wingenbach C, Hilpert S, Gunther S. The core concept of the Open Energy
Modelling Framework (oemof). In: Environmental Informatics { Current trends
and future perspectives based on 30 years of history; 2016.

**Comment by fraukewiese** [comment]
Citation in the text is not consequent yet. Two versions:
[65] argues
Hilpert [69] argues
Don't know if this matters

**Comment by gplssm** [comment]
@fraukewiese thanks for taking a closer on it and doing more detailed work!
To be honest, I only took care about references list and not how they are used in the text.
Recently, a copy-editor advised me to use the format or Ref. [65] if I include the reference in the text.

I would recommend to change your above example to

Ref [65] argues
Hilpert [69] argues

But I like the format of the second line more!

**Comment by ckaldemeyer** [comment]
> I would recommend to change your above example to
> 
> Ref [65] argues
> Hilpert [69] argues
> 
> But I like the format of the second line more!

I think the latter is only valid if it's a single author, isn't it?

Otherwise it should be either "et al." or the first version with "Ref" which could of course also be used for single authours.

I could deal with it since I am revising right now and would suggest to use "Ref" to get it straight and uniform, if you all agree @gplssm @fraukewiese @simnh @gnn @uvchik @cswh

**Comment by simnh** [comment]
I think names are good, but in this case no et.al. needed because one author... Do not bother too much, I guess there will be feedback from the journal. Just make it coherent.. @ckaldemeyer : you decide...

**Comment by ckaldemeyer** [comment]
> I think names are good, but in this case no et.al. needed because one author... Do not bother too much, I guess there will be feedback from the journal. Just make it coherent.. @ckaldemeyer : you decide...

No problem. It was just a hint

**Comment by uvchik** [comment]
:+1:  :+1:  für "...Hilpert [69] argues..." oder "...Hilpert et al. [69] argue...".

Nach den Zitierregeln, die ich kenne muss ein Satz immer als Satz lesbar und verständlich sein. Der Verweis auf die Quelle ist dabei eine (wichtige) Zusatzinformation die aber nicht sinngebend sein darf, also nicht das Subjekt ersetzen darf. Abgesehen davon, dass ich das beim Lesen auch grausig finde.

Damit widerspricht [35] der Aussage von [56], obwohl in [47] beide Aussagen als passend bezeichnet werden.

Wenn das Journal das anders sieht müssen wir das natürlich entsprechend ändern.

**Comment by ckaldemeyer** [comment]
> für "...Hilpert [69] argues..." oder "...Hilpert et al. [69] argue...".
> 
> Nach den Zitierregeln, die ich kenne muss ein Satz immer als Satz lesbar und verständlich sein. Der Verweis auf die Quelle ist dabei eine (wichtige) Zusatzinformation die aber nicht sinngebend sein darf, also nicht das Subjekt ersetzen darf. Abgesehen davon, dass ich das beim Lesen auch grausig finde.

Damit kann ich mich auch sehr gut anfreunden bzw. finde es auch schöner. Die Variante von Guido (Ref[x]) habe ich aber auch schon häufig gelesen und scheint im Englischen verbreitet zu sein.

Ich versuche das dann mal so zu berücksichtigen..
