### ISSUE TITLE
Include some lines for usability from a user perspective 

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#41]
this might end up in a section 'usability and applicability' or somewhere else, but as discussed here #32 it should be included and is still missing. This may also link to reuse of existing code....and not 'reinventing the wheel' (which by the way is somewhere in the text and should go out...)

**Comment by simnh** [comment]
I did this, you might want to extend this one just a little?

**Comment by uvchik** [comment]
Ich glaube es ergibt Sinn, wenn wir kurz ein paar Dinge klarstellen bevor ich konkrete Textvorschläge mache. Wenn Du das anders siehst, dann gib bitte kurz Rückmeldung.

**Usebility Absatz:** Wenn ich das "Benutzerfreundlichkeit" dann richtet es sich doch an die Nutzenden des Frameworks. Das sind aber doch in erster Linie Leute die Apps schreiben bzw. sie dann auch benutzen, also mit Daten füllen und Ergebnisse nutzen. Das sollten aber doch versierte Leute sein. Oder willst du auf den Punkt hinaus, dass das Framework die Sache nun so stark vereinfacht und damit Leute "verführt" Modelle zu bauen die nicht verstehen, was sie da tun? Ich kann den Absatz gerne nochmal überarbeiten, aber wir sollten uns vorher nochmal kurz über das Ziel einig sein.

**applicability Absatz:** Der richtet sich doch an die App-Schreiber bzw. Contributer, oder? Also warum schreiben die Leute eigene Modell statt bestehende zu nutzen und wie kann dem begegnet werden. Bei oemof müssen wir da m.E. noch irgendwie trennen zwischen Leuten die oemof Apps schreiben und Leute die das Framework erweitern mit ihren Ansätzen.

**Comment by simnh** [comment]
Zuerst: challenges beziehen sich auf all arten von modellen und nicht auf oemof. Eigentlich wird es ja in der section definiert, was unter usability udn was unter applicability zu verstehen ist.

**Comment by uvchik** [comment]
Vielleicht verstehe das Paper nicht richtig oder habe eine entscheidene Stelle überlesen. Ich dachte es geht um Modelle, die sich an Wissenschaftler und Modellierer wenden. Modelle, die sich direkt an Entscheidungsträger wenden gehören meines Erachtens in eine andere Kategorie. Modelle wie Calliope, Urbs, Osemosys, renpass, balmorell, psPSA richten sich doch nicht an Entscheider. Ich finde, das in dem Absatz bzw. in der Definition nicht scharf genug getrennt. Mich hat das verwirrt.

Wenn Du findest, dass eine solche Anmerkung zum jetzigen Zeitpunkt zu spät kommt, dann ziehe ich sie zurück und beschränke mich auf "einfach lesen und ggf. fehler korrigieren".

Konzentriere mich zunächst auf #53 und melde mich falls ich hier noch was machen sollte.

**Comment by fraukewiese** [comment]
Die Ergebnisse von e.g. Osemosys richten sich direkt an Entscheidungstraeger. Kaum ein Modell wird nur klar abgetrennt fuer "wissenschaftliche Zwecke" verwendet. Und wenn e.g. die Gruenen bei Euch eine Studie 100% EE Brandenburg und Berlin in Auftrag geben und ihr das modelliert mit oemof, dann richten sich die Ergebnisse ja schon an Entscheidungstraeger. Und fuer was machen wir denn das ganze Herummodellieren wenn nicht um eine besserer Grundlage fuer Energiepolitische Entscheidungen zu bieten. Direkt oder indirekt. Dazu auch die Aim von der openmod-initiative Seite:
"Open models and open data will advance knowledge and lead to better energy policies. Open up energy models improves quality, transparency, and credibility, leading to better research and policy advice."
Und ich wuerde auch sehr dafuer plaedieren nicht nochmal alles aufzurollen in dem paper, man kann es sicher anders machen, strukturieren, anderen Fokus etc., aber das ist dann fuer was auch immer fuer ein naechstes paper :)

**Comment by simnh** [comment]
danke @frauke für die ausführung. Ich möchte nur noch folgendes hinzufügen: 

Für mich steht ist ein zentraler punkt der discussion udn ggf. conclusion eben genau der: 

model werden als Tool bei der entscheidungsgrundlage genutzt daher ist die richtige verwendung der ergebnisse elementar....zu Hause kann ja gerne jede/r rechnen was sie/er will :)

**Comment by uvchik** [comment]
@fraukewiese wrote:
> Und ich wuerde auch sehr dafuer plaedieren nicht nochmal alles aufzurollen in dem paper [...]

@simnh wrote:
> Die section ist jetzt in 'Review QA' Pipline. Also einfach lesen und ggf. fehler korrigieren und möglicherweise Sachen hinzufügen bzw. feedback geben.

Ich will doch gar nicht alles umwerfen, aber Eure Beiträge wirken auf mich so als hätte ich das geschrieben. Wenn das so verstanden wurde, dann möchte ich an dieser Stelle nochmal deutlich machen, dass dem nicht so ist.

Ich wollte lediglich versuchen die Ebenen klarer abzugrenzen. Ich finde die Programmierenden von oemof müssen dabei auf andere Dinge achten, als die Programmierenden einer App und erst recht als die Studieschreiber bei denen es dann ja um das Zusammenspiel von Daten und Modell geht. Für mich können das bis zu 3 verschiedene Personen sein (natürlich auch nur 1). Und die drei Personen haben unterschiedliche Verantwortung und müssen auf andere Sachen achten. Ich dachte man könnte das mit 1-2 zusätzlichen Sätzen besser abgrenzen. So hatte ich das issue halt verstanden.

@simnh wrote
> I did this, you might want to extend this one just a little?

Wenn Ihr das so gut findet, wie es ist, dann ziehe ich das jetzt also zurück und kümmere mich um #53.

**Comment by simnh** [comment]
Du hast ja recht, aber ich glaube es gibt ein missverständis über die section. Die section bezieht sich nicht (kein bisschen) auf oemof. daher kann die trennung in developer, user und decision maker. und die beziehugnen untereinander. Ich denke schon, dass es sinn macht sachen klarer rauszuarbeiten, wenn du noch denkst, dass es nötig ist. es muss aber zuerst klar sein auf was die section abzielt, und diese hat wie gesagt nichts mit oemof zu tun. mach doch einfach einen pull request, wenn du noch zwei sätze hinzufügen kannst die es klarer machen. 
 ich würde mihc freuen!

**Comment by uvchik** [comment]
Im direkten Gespräch mit @simnh haben wir festgestellt, dass wir uns entscheiden müssen, wo wir die Grenze für das Paper ziehen.

1. **Modellentwicklung:** Dann wären die Probleme der Kommunikation nur der Aufhänger und daraus folgen dann die Anforderungen für die developer-user kommunikation. Also: Was müssen Developer in der Kommunikation mit Usern sicherstellen, damit die alle Informationen besitzen um die Annahmen bezogen auf die Ergebnisse vollständig erfassen zu können. Gilt nicht nur für frameworks sondern auch für Modelle wie caliope, urbs, Balmorell etc..  Bezogen auf oemof haben wir festgestellt: Schon ganz gut, aber es gibt auch Lücken)
2. **Anwendung:** Dann wäre die Anwendung von oemof, caliope, Balmorell etc. (also z.B. eine Frankreichstudie, die mit renpassgiss oder Balmorell gemacht wird) noch Bestandteil des Papers.

Meiner Meinung nach müssten wir im 2. Fall zumindest die Ebene der Daten noch erwähnen. Den die Transparenz solcher Ergebnisse entsteht erst im Zusammenspiel zwischen den Annahmen des Modells und den Annahmen der Daten. Eins kann nicht ohne das andere gedacht werden. Da ich die Daten gerne rauslassen würde, würde ich den Schnitt bei 1. machen.

@simnh wird das noch klarstellen. 

In beiden Fällen können die Textblöcke weitestgehend erhalten bleiben nur der rote Faden, also die Übergänge werden dann angepasst. bzw. Sätze ergänzt.

Ich hoffe ich habe das so richtig wiedergegeben.

**Comment by simnh** [comment]
I decided to include application as we have this inside uncertainties as well with our literature based on Mirakyan2015. And for me, this absolutely makes sense.

**Comment by uvchik** [comment]
Ich habe Mirakyan nicht komplett gelesen (fast 70 Seiten), aber ich habe den Eindruck, dass er nicht von OpenSource Modellen spricht. Erst durch offene Modelle kann diese starke Trennung zwischen Developer und User entstehen (natürlich können die trotzdem gleich sein).

Für mich gehören Applikationen auch dazu, aber nicht das Produzieren von Ergebnissen für eine Zielperson oder Zielgruppe. Meinem Empfinden nach geht es in dem Paper sonst an keiner Stelle darum. Daher empfinde ich den Abschnitt als Bruch mit dem "roten Faden". Für mich geht es in dem Paper um die Herausforderungen an Modelle. Ginge es generell auch um Ergebnisse und Studien könnten auch noch weitere Challenges dazu kommen. Auch die Anforderungen an die Daten könnten dann noch eine Rolle spielen.

Das ist aber nur  meine Meinung. Da wir nicht mehr viel Zeit haben sollten die Diskussion besser abbrechen. Du bist Hauptautor und damit hast Du die Entscheidung getroffen. Ich werde mal gucken, ob mir noch Aspekte einfallen die fehlen (wie besprochen).

**Comment by uvchik** [comment]
In der Diskussion könnte dann vielleicht heraus gearbeitet werden, dass die, die offene Modell herausbringen nur dafür verantwortlich sind inwiefern sie so gut dokumentiert sind, um die user zu befähigen die user-Entscheider Kommunikation zu führen. Sie können diese aber nur sicherstellen, wenn sie ihr Modell so eng stricken (inkl. Daten), dass eine Variation nur in ganz engen Grenzen möglich ist. Damit steht dieser Punkt im Widerspruch zu flexiblen Modellen (zumindest was die Verantwortung für die user-Entscheider Kommunikation betrifft, nicht, was die developer-user Kommunikation angeht).

**Comment by uvchik** [comment]
So in etwa (-> b88ff0c)?
