### ISSUE TITLE
Author order

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#43]
We need to define a order. I propose the following: 

We use alphabetic order (surname oder name), yingyang sign for me and double dagger for all others.
I pushed that already. Essentially this means: 

Everyone contributed equally to this work, acknowledging oemof development, except me, because I am boss of paper ;) 

Please feel free to suggest other orders...You may then discuss here.

**Comment by ckaldemeyer** [comment]
Double thumbs up from my side. I think this is a really good solution!

**Comment by fraukewiese** [comment]
Great, plos1 has a nice way of being able to do this.
I have changed my affilation to DTU as I spend time for this now.

**Comment by gplssm** [comment]
If I remember right, last time we draw a decision on author order, we said that we respect both contribution to oemof development and contribution to this paper by author order. I really liked that decision!

I like these markers to state equal contributions as well! But, it is not clear for me how we give a hint about code contribution. @simnh could you please explain or even show?

**Comment by simnh** [comment]
Do you meand authors or other people as well?

**Comment by fraukewiese** [comment]
When I get your point right @gplssm code contributions to oemof by people (authors and other people) can be dealt with in the Acknowledgement section, see #57 
Would that be fine with you? Then it is e.g. clearly stated that I have not contributed to oemof code.

**Comment by ckaldemeyer** [comment]
> When I get your point right @gplssm code contributions to oemof by people (authors and other people) can be dealt with in the Acknowledgement section, see #57
Would that be fine with you? Then it is e.g. clearly stated that I have not contributed to oemof code.

For me :+1:

**Comment by gplssm** [comment]
Thanks for explanation! I understand.

**Comment by uvchik** [comment]
At the moment I linked to the github page (s. dbe5bca07). If it is okay like this, I could add the citations.

1. Shall I name the developers?
3. Do want me to write it more extensive?

**Comment by simnh** [comment]
I think the info that authors and developers are not identical is good. We do not need to name developers but we might be a little more extensive on the acknowledge section: 
 
- oemof is a collaborative project, builds on the contribution of many many developers
-  ...

feel free :)

**Comment by ckaldemeyer** [comment]
Ich habe meinen Senf dazu in #33 abgegeben. Insgesamt würde ich im Framework-Teil eine kurze Info über die initiativ an der Entwicklung beteiligten Institute fallen lassen und dann auf die Acknowledgements verlinken, wo alles nochmal ein bisschen ausführlicher erläutert wird.
