### ISSUE TITLE
Add literature to overview table at challenges section

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#44]
We might add citations to the table in section 2 at the beginning.

**Comment by simnh** [comment]
I added all the literature to the table. Can somebody review, if the literature added is correct: 

* literature fits to the challenge
* literature is mentioned inside the subsection of the specific challenge below the table

**Comment by uvchik** [comment]
Ist das üblich so? 

Ich würde die Tabelle als eine Art "zusammenfassender Überblick" werten und daher meinen, dass die Literaturverweise nicht notwendig sind, da sie ja im Text auftauchen. Zudem ist die Tabelle dann etwas luftiger.

**Comment by uvchik** [comment]
@simnh : Wenn Du das aber gerne so behalten willst gucke ich mal drüber. Ich wollte nur sicher gehen.
