### ISSUE TITLE
Include Agent based modelling in challenges

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#46]
We do not work with agent based modelling, but we should metion it, as it is surely an existing/emerging approach to some challenges and it is missing in the paper.

**Comment by simnh** [comment]
Cant access right now, just as a reminder:
http://www.sciencedirect.com/science/article/pii/S1364815215001231
http://www.sciencedirect.com/science/article/pii/S0306261915005346

**Comment by simnh** [comment]
I assigned all the ones assigned to the challenges section. Please see, how and where agent-based modelling fits to your challegens as a emerging or existing approach (I assume rather at: Complexity, Interdisciplinarity)

**Comment by simnh** [comment]
Reeg, M. et. al, Weiterentwicklung eines agentenbasierten
Simulationsmodells (AMIRIS) zur Untersuchung des Akteursverhaltens bei
der Marktintegration... /

**Comment by fraukewiese** [comment]
Agent-based literature is included now in Complexity #29 and Interdisciplinarity #31.
@simnh : would suggest to close the issue

**Comment by simnh** [comment]
Looks good, Thanks a lot
