### ISSUE TITLE
Energy model definition and literature review

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#48]
We talk a lot about energy models, but we neither define them nor do we provide a overview of state of art applied and existing models. Should we do that?

**Comment by simnh** [comment]
The minimal approach should be an extensive delimitation of our approach in the 'framework' section

**Comment by simnh** [comment]
This is linked to: #33

**Comment by simnh** [comment]
I think I proposed a good compromise by adding some lines to the introduction of challenges. Who can review this one? (see also #26 )

**Comment by fraukewiese** [comment]
I will review that now: First paragraph of challenges, right?

**Comment by simnh** [comment]
yes, do not wonder there is no definiton and literature review, but at least something ...feel free to extend

**Comment by fraukewiese** [comment]
I pushed the introduction section of the challenge chapter. I think it is very good and sufficient what you wrote about energy system models, Simon, I just changed the bridge to challenges a bit.
So can we close this issue?

**Comment by simnh** [comment]
Yeah I think this one can be closed
