### ISSUE TITLE
Section Applications

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#53]
There are quite a lot of comments within the application section that contain ideas about the text and figures. So this section needs a remastering, too..

**Comment by ckaldemeyer** [comment]
I hope this was in line with the general workflow..

**Comment by simnh** [comment]
> There are quite a lot of comments within the application section that contain ideas about the text and figures. So this section needs a remastering, too..

Actually, that is meant by 'task' :)

**Comment by uvchik** [comment]
@ckaldemeyer Heißt das, dass Du da dran bist? Ich würde den Text über reegis_hp korrigieren und deutlich machen, dass es natürlich noch weiter Apps (veröffentlichte und nicht veröffentlichte) gibt. In dem Rahmen könnte ich mir auch das ganze Kapitel nochmal vornehmen.

**Comment by simnh** [comment]
@ckaldemeyer  is doing an other section you can do it @uvchik . Best way is a pull request for the applications section.  @gnn  is working on the framework section...you might want to check with him.

**Comment by uvchik** [comment]
Dann spreche ich mich mit @gnn ab und werde mich morgen (23.12.) um diese Section kümmern.

**Comment by ckaldemeyer** [comment]
@uvchik Legt da ruhig los. Ich setze mich jetzt an die Challenges!

**Comment by uvchik** [comment]
Habe versucht die Anmerkungen einzuarbeiten und die Schrift so groß wie möglich zu machen, basierend auf der Version, die ich hatte. Wenn die Rechtecke länglich sind kann die Schrift größer sein und der leere Platz unten links fällt weg (vgl. derzeitiges Bild unten).

![oemof_paper_neu](https://cloud.githubusercontent.com/assets/4760584/21457292/71e5d340-c92e-11e6-9b42-bd2f5f8ee919.png)

Bildunterschrift: 
Building an application based on libraries of the oemof cosmos and external libraries (dark grey).

![altes_bild](https://cloud.githubusercontent.com/assets/4760584/21457427/8b35b68e-c92f-11e6-90f3-923e0f7d2028.png)

**Comment by simnh** [comment]
sieht besser aus, pusht du das auf einem feature branch oder wo arbeitest du ?

**Comment by uvchik** [comment]
-> #61

**Comment by uvchik** [comment]
Ja, mach ich.

**Comment by uvchik** [comment]
Closed by #61 (merged)
