### ISSUE TITLE
Add powerflow literature (e.g. Müller et.al) for applications section

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#62]

**Comment by simnh** [comment]
Also adding: 

Möller etc., and Vernetzen

**Comment by simnh** [comment]
I added the literature and will add citation once @gnn  fininishes the framework section...If you have oemof literature please add this as well..

**Comment by ckaldemeyer** [comment]
Wir haben bisher nur unseren Projektbericht für das Druckluftspeicherkraftwerk und unser CAES Paper von der letzten IRES. Das Paper hat die Modellierung mit oemof nur im Ausblick und ich denke, dass ich es lieber nicht referenzieren würde. Den Bericht könnte man evtl. anführen, da er später auch unter einer ISSN veröffentlicht werden soll. Allerdings ist er auch auf Deutsch verfasst.

Meine Tendenz: beides eher nicht anführen und eher bei Englischen "richtigen" Papers bleiben.

**Comment by simnh** [comment]
brauch auch eh nur noch was von den RLI fpr power.-heat - transport ;)

**Comment by uvchik** [comment]
Bei uns sind das aber auch eher Berichte in deutscher Sprache.
