### ISSUE TITLE
Coherent Wording

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#67]
* Python vs. python 
* apps vs. applications 
* combined words with or without - (e.g. work-flow or workflow ? )

**Comment by simnh** [comment]
The ones up there I did

**Comment by ckaldemeyer** [comment]
Something I stumled upon (also in other contexts) is "open source".

According to some wikipedia articles:

* https://en.wikipedia.org/wiki/Free_and_open-source_software
* https://en.wikipedia.org/wiki/Open-source_software

it is "open-source" and according to the FSF it os "open source":

https://www.gnu.org/philosophy/open-source-misses-the-point.en.html

The definitions hold for German and English.

My preference would be "open source"!

**Comment by simnh** [comment]
As there are different options we just stick to one, right now it's open source as we tried to avoid words with '-' if possible. So thats in line with your preference

**Comment by ckaldemeyer** [comment]
:+1:

**Comment by ckaldemeyer** [comment]
Ich glaube das ist hier nicht der perfekte Platz für mein Anliegen aber so grob passt es und da es ohnehin sehr klein ist, schreibe ich es einfach hier rein:

Ich würde in den Challenges-Überschriften das "Challenge:" wie z. B. bei "Challenge: Complexity" grundsätzlich weglassen, da es m. E. unschön aussieht und aufdoppelt.

Das es eine Challenge ist, geht ja eh aus der Struktur hervor:

* Challenges in Energy System Modelling
  * [Challenge:] Complexity
  * usw.

Analog ist es bei den Addressed Challenges:

* Addressed Challenges
   * [Addressing:] Complexity
   * usw.

Was meint ihr dazu?

**Comment by ckaldemeyer** [comment]
Ansonsten bin ich gerade über den PR-Branch geflogen und finde,  dass es schon sehr gut aussieht! V.a. die Tabelle am Ende passt in Proportion zum Text, etc.

Danke schon mal an @simnh und @fraukewiese !

**Comment by simnh** [comment]
Das Ding ist, dass PLOS1 halt keine Nummerierung hat und auch kein Inhaltsverzeichnis am Anfang (soweit ich weiß). Daher finde ich es doppelt eigentlich nicht auf sondern macht es eher klar...Aber eröffne doch einfach ne Abstimmung, mir is das latte...

**Comment by ckaldemeyer** [comment]
> Das Ding ist, dass PLOS1 halt keine Nummerierung hat und auch kein Inhaltsverzeichnis am Anfang (soweit ich weiß). Daher finde ich es doppelt eigentlich nicht auf sondern macht es eher klar..

Man sieht es doch so doer so an der Überschriftenformatierung. 

> Aber eröffne doch einfach ne Abstimmung, mir is das latte...

Mache ich

**Comment by ckaldemeyer** [comment]
Gibt es für Abstimmungen einen github-Plugin?

Ansonsten schreibt hier bitte einfach eure Meinung dazu, also "Challenge: som Challenge" bzw. "Addressed Challenge: some Addressed Challenge" ja oder nein?

**Comment by ckaldemeyer** [comment]
> Ansonsten schreibt hier bitte einfach eure Meinung dazu, also "Challenge: som Challenge" bzw. "Addressed Challenge: some Addressed Challenge" ja oder nein?

Nein

**Comment by simnh** [comment]
> Gibt es für Abstimmungen einen github-Plugin?
ja gibt es (zumindest macht guido das immer in pull requests...

**Comment by ckaldemeyer** [comment]
> ja gibt es (zumindest macht guido das immer in pull requests...

Habe ad hoc nix gefunden. Aber es geht ja auch so und @gplssm kann ja evtl. für's nächste Mal nen Link oder so posten

**Comment by simnh** [comment]
I think this is pretty much done
