### ISSUE TITLE
Condense section uncertainty to really necessary aspects

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#7]
Do you think [this](https://github.com/simnh/addressing_challenges_oemof/blob/529b87c9951a1fe72e9e6451060317c9538d8830/challenges_of_energy_system_modelling.tex#L172-#L178) still fits in this section of the paper or in general in the paper?

**Comment by fraukewiese** [comment]
Sorry for not answering earlier. Do you mean the orange marked paragraph starting with "in contrast to uncertainty..." ? If yes, I think this fits
