### ISSUE TITLE
Externer Korrekturleser?

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#72]
Hallo zusammen,

vor der entgültigen Einreichung wäre es meiner Meinung nach noch einmal sinnvoll einen "oemof-Externen" mit Erfahrung im wissenschaftlichen Publizieren das Paper gegenlesen zu lassen.

Dabei ginge es weniger darum die Struktur umzuschmeissen (bloß nicht! ich denke sie ist auch gut so..) sondern auf allgemeine Elemente (roter Faden, Gewichtung der einzelnen Kapitel, Umfang der Literaturauswahl, ...) zu prüfen.

Ich denke das würde zudem die Gefahr reduzieren, dass wir in unserer oemof-Logik zwar alle wissen wovon wir reden, einem Externen aber an geeigneter Stelle eine wichtige Information fehlt.

Als Personen hätte ich ad hoc die folgenden Ideen:

* Olav Hohmeyer (Prof. EUF)
* Ilja Tuschy (Prof. HSF)
* Bernd Möller (Prof. EUF - mein Favorit, aber man müsste erstmal fragen, ob er das übernehmen würde)
* jemand vom RLI?

Was meint ihr dazu?

Grüße
Cord

**Comment by ckaldemeyer** [comment]
Sagt mal bitte, was ihr dazu meint

**Comment by fraukewiese** [comment]
Genau dafür gibt es den Peer-Review Prozess. Das heißt mein klares Votum ist: Einreichen und genau diese Qualitätsprüfung die anonymen Peer-Reviewer machen zu lassen. Ich denke es ist auf jeden Fall gut genug, dass sie es nicht durchfallen lassen. Meiner bisherigen Erfahrung nach ist das Feedback aus dem Peer-Review-Prozess sehr viel hilfreicher und man muss es sowieso machen, da gibt es bestimmt sowieso nochmal ne Iterationsrunde da es fast nie ohne geforderte Änderungen durchkommt.

Würden wir Olav fragen dauert es ewig, mit Ilja müsste man sich vermutlich um Kleinigkeiten streiten, Bernd Möller ist so gar nicht drin in der Open Source Geschichte. Inzwischen ist das Paper auf einer Stufe wo Leute wie die drei sicherlich arbeitsintensive Änderungsvorschläge haben, aber die Peer-Reviewer sicherlich andere Änderungsvorschläge haben werden. Also lasst uns auf die letzteren konzentrieren :)

Meist fordern einen die Journals dazu auf, Reviewer vorzuschlagen. Ich hatte in irgendeinem Issue das ich gerade nicht mehr finde schon mal eine Liste angefangen und Guido hatte sie ergänzt. Das kann nicht Olav etc. also zu nahe Personen sein, aber wir können welche wählen von denen wir auch wirklich gerne Input haben möchten zum Paper.

**Comment by simnh** [comment]
Ich sehe es wie Frauke, trotzdem sollten alle mit autoren nochmal lesen, ob sie auch mit dem einverstanden sind was eingereicht wird....

**Comment by ckaldemeyer** [comment]
> Genau dafür gibt es den Peer-Review Prozess. Das heißt mein klares Votum ist: Einreichen und genau diese Qualitätsprüfung die anonymen Peer-Reviewer machen zu lassen. Ich denke es ist auf jeden Fall gut genug, dass sie es nicht durchfallen lassen. Meiner bisherigen Erfahrung nach ist das Feedback aus dem Peer-Review-Prozess sehr viel hilfreicher und man muss es sowieso machen, da gibt es bestimmt sowieso nochmal ne Iterationsrunde da es fast nie ohne geforderte Änderungen durchkommt.
> 
> Würden wir Olav fragen dauert es ewig, mit Ilja müsste man sich vermutlich um Kleinigkeiten streiten, Bernd Möller ist so gar nicht drin in der Open Source Geschichte. Inzwischen ist das Paper auf einer Stufe wo Leute wie die drei sicherlich arbeitsintensive Änderungsvorschläge haben, aber die Peer-Reviewer sicherlich andere Änderungsvorschläge haben werden. Also lasst uns auf die letzteren konzentrieren :)
> 
> Meist fordern einen die Journals dazu auf, Reviewer vorzuschlagen. Ich hatte in irgendeinem Issue das ich gerade nicht mehr finde schon mal eine Liste angefangen und Guido hatte sie ergänzt. Das kann nicht Olav etc. also zu nahe Personen sein, aber wir können welche wählen von denen wir auch wirklich gerne Input haben möchten zum Paper.

Du hast mich auch überzeugt! Allerdings sollte jeder wirklich noch einmal draufschauen, bevor es rausgeht ;)

Zu den Personen gab es wirklich mal Liste. Ich meine z. B. mit Tom Brown, David Kleinhans, ...

**Comment by ckaldemeyer** [comment]
Ich mache heute nochmal meinen Grobschliff fertig und schreibe eine TODO-Liste mit den Dingen, die noch fehlen und die ich zeitlich nicht mehr schaffe. Danach kann ja jeder nochmal draufschauen.

**Comment by gplssm** [comment]
Ich sehe es auch so, dass wir einen recht guten Stand erreicht haben und bald submitten können. Ich stimme Simon zu, dass jedeR AutorIn den gegenwärtigen abnicken bzw. nochmal Dinge kritisieren sollte und wir diese alsbald umsetzen.
@simnh Gibt es zum Korrekturlesen nun ein Vorgehen oder lesen wir alle einfach individuell (in den nächsten Tagen) drüber und geben eine Rückmeldung?

**Comment by simnh** [comment]
einfach korrekture bitte direkt im text und auch größere sonst als pull request, sprich vorschlag...am besten nachdem cord fertig ist und dann in den master gemergt hat. dann davon einen neuen branch abzweigen,... also ab morgen denke ich @ckaldemeyer  ?

**Comment by ckaldemeyer** [comment]
> einfach korrekture bitte direkt im text und auch größere sonst als pull request, sprich vorschlag...am besten nachdem cord fertig ist und dann in den master gemergt hat. dann davon einen neuen branch abzweigen,... also ab morgen denke ich @ckaldemeyer ?

Ab Morgen Mittag bin ich durch! Poste dann nochmal hier..

**Comment by ckaldemeyer** [comment]
Ich habe jetzt meine Änderungen vorgenommen und alle verbleibenden TODOs als Kommentare an die jeweilige Stelle bzw. hinten unter TODOs geschrieben.

Allgemein habe ich folgende Änderungen vorgenommen:

* Generelles Prüfen und ggf. Ändern von Formulierungen und Fehlern
* Hinzufügen von Inhalten wo welche fehlten bzw. es zu dünn war
* Allgemeine optimische Abstimmung von Listen, etc. (ich habe teilweise Text in Listen gewandelt und teilweise Listen in Text, um den Listeninhalten ein entsprechendes Gewicht beizumessen) 
* Zitierweise (et. al, according to bla et al.)
* Wording
* Abstimmung von Textteilen
* ....

Die ausstehenden TODOs habe ich möglichst kleinteilig ausformuliert, damit sich ggf. jeder welche raussuchen kann.

@simnh kann dann ja die weiteren Schritte definieren!
