### ISSUE TITLE
Formatting of Parargraphs

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#74]
Paragraphs need to be formatted in a final way...at least content wise...

**Comment by simnh** [comment]
As everyone should read the paper, please check how you would group / degroup paragraphs while reading...lets try 'schwarm-intelligenz' :)

**Comment by fraukewiese** [comment]
ok, but I think it is not so important

**Comment by fraukewiese** [comment]
I will read this Friday. I think the general perspective when reading again by all authors should be: Change obvious mistakes, do not try to change general stuff unless you cannot live with it.
@simnh : What is the deadline for reading again? I do it Friday. What about Tuesday? Actually I do not have the need to read it anymore as I trust you two having done a great job, but as it is your wish I do :)

**Comment by gplssm** [comment]
Ich lese das Paper morgen.

**Comment by simnh** [comment]
Super, danke guido und allen anderen.
