### ISSUE TITLE
Suggested peer-reviewer

### ISSUE THREAD

**Issue by fraukewiese** [simnh/addressing_challenges_oemof#77]
If plos 1 asks for suggestions for peer-reviewer, let us make a list here:
- Tom Brown
- David Kleinhans
- Hans Ravn
- Mark Howells

**Comment by gplssm** [comment]
Old discussion about suggested reviewers: #18

**Comment by ckaldemeyer** [comment]
> Old discussion about suggested reviewers: #18

Habe die Liste in diesem Issue mal entsprechend ergänzt.
