### ISSUE TITLE
Mittel für Open Access Publikation

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#80]
Wir sollten nicht vergessen die Mittel rechtzeitig zu beantragen, um die Cofinanzierung durch die EUF/HFL zu bekommen.

Wann genau müssen die Mittel bereitgestellt werden? Schon zum Review-Prozess?

**Comment by simnh** [comment]
Ne, soweit ich weiß erst wenn azeptiert und reviewed ist... also publiziert

**Comment by fraukewiese** [comment]
Ja, die Rechnung kommt wenn finally accepted, dann allerdings Zahlung innerhalb von so 2 Wochen (zumindest war es bei nem anderen Journal so)
