### ISSUE TITLE
Correct literature for els-format

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#83]
Wer kann das machen? Zumindest schon mal einen Aufschlag?

**Comment by simnh** [comment]
Außerdem dabei direkt nochmal auf Retschreibung etc mit gucken bei den Quellen...

**Comment by simnh** [comment]
Text:
Indicate references by number(s) in square brackets in line with the text. The actual authors
can be referred to, but the reference number(s) must always be given.
List:
Number the references (numbers in square brackets) in the list in the order in which they appear
in the text.

**Comment by simnh** [comment]
Ok I started and remove a lot unnecessary stuff what is still missing ist: 

PLEASE DO NOT OPEN THE FILE WITH JABRAF or similar, only plain text editor. Otherwise it will fill in data we do not want there

TODO's

* [ ] check alls Misc types: We still need a nice why to include the url there and the information on when last accessed. Search for DOI, if available include, and remove the other stuff (i.e. url etc...) 
* [ ] Last proff reading
* [ ] Add dois if available...

**Comment by simnh** [comment]
I still need to push, what I will do today...

**Comment by gplssm** [comment]
Hast du deine letzten Änderungen nun gepusht? Ich könnte mich da heute nochmal ransetzen...
Kannst du vielleicht auch kurz sagen wo ich ggf. weitermachen soll? Habe nicht ganz den Überblick.

**Comment by simnh** [comment]
ja habe ich...ich habe issues angelegt zu den themen eine übersicht gibts in #81

**Comment by gplssm** [comment]
Den Typ Misc für Webseiten würde ich in der Formatierung einfach halten. Folgender Vorschlag anhand erster Internetquelle
```
[14] Opemod Initiative (open energy modelling initiative), Open Models, http:
//wiki.openmod-initiative.org/wiki/Open_Models, Accessed 24 June
2016.
```

Folgendes habe ich gemacht
- `year = {}`
- url verwendet
- Title und author in {{}} gesetzt
- "Available online" entfernt

Was denkt ihr?

**Comment by simnh** [comment]
Ja kann man so machen, bei manchen ist aber das jahr vielleicht auch gar nicht schlecht, weil die veröffentlichung in einem anderen Jahr statt gefunden hat als der zugriff...? 
ansonsten wäre vielleicht der link unter url = 'http...' 
besser ? 

aber mach wie du denkst, hauptsache einheitlich und auffindbar ;)

**Comment by fraukewiese** [comment]
@gplssm , sagst du bescheid wenn ich da noch unterstuetzen kann/soll? heute nachmittag und dienstag koennt ich was machen. entweder zu den quellen oder komplettes document dann checken @simnh

**Comment by gplssm** [comment]
@simnh Ich verstehe deine Intention bzgl. der Angabe von "year". Allerdings finde ich das Resultat mit der Jahreszahl in Klammern hinter dem Access date eher verwirrend. Es mag interessant sein für den Leser, in welchem Jahr die Seite online gegangen ist. Allerdings wollen wir ja einen Stand der Webseite referenzieren und dafür ist das Zugriffsdatum relevant. Wie alt die Seite tatsächlich ist, ist eher uninteressant und teilweise auch schwer herauszufinden (was dann wieder der Einheitlichkeit widerspricht).

Ich kann die URL auch in "url ={...}" packen. Das hat zur Folge, dass (a) das URL vor dem Link steht und (b) der Titel der Webseite auch ein Hyperlink wird. Sehe da jetzt nicht direkt den Vorteil und würde tendenziell bei meinem Vorschlag bleiben. Bei guten Argumenten oder nachdrücklichem Wunsch bin ich zu allem anderen bereit... 

@fraukewiese du kannst gerne unterstützen. :+1:  Habe gestern abend nicht mehr viel gemacht und komme wahrscheinlich erst am WE wieder dazu. Ich würde folgendes machen

1. Alle @misc auf einheitliches Format bringen
2. DOIs zu anderen Referenzen hinzufügen (falls möglich)
3. Gesamtcheck der Referenzen, also noch einmal alles durchgehen

Wenn du davon bereits etwas übernimmst, gib Bescheid.

**Comment by simnh** [comment]
@gplssm ja alles super! du /ihr  mach(s)t das schon...

**Comment by fraukewiese** [comment]
wegen #87 mach ich da erstmal nicht weiter (entschuldige Guido), denn wer weiss was das fuer die Referenzen nach sich zieht.

**Comment by gplssm** [comment]
Brauchst dich nicht entschuldigen, wir warten einfach die Entscheidung ab und dann machen wir entsprechend weiter.

**Comment by gplssm** [comment]
Ich bin jetzt einigermaßen stur die @misc Referenzen durchgeganen und habe auch Reports, die auf einer Website veröffentlicht sind mit "Accessed ..." versehen. Ebenso habe ich für @misc Einträge, die Reports wiedergeben, das Veröffentlichungsjahr in Klammern angegeben.  Gibts da Einwände?

Weiterhin bin ich die gesamten Referenzen im PDF nochmal durchgegangen und hab nach DOIs und "korrektem Aussehen" geschaut.

@simnh oder @fraukewiese ihr könnt das gerne nochmal gegenprüfen. Andernfalls, könnt ihr mir einfach trauen und wir schließen das Issue ;-)

**Comment by fraukewiese** [comment]
super, ich bin für schließen. habe gerad nochmal alles gelesen (bis auf die referenzen), im text fehlen nur die beiden Referenzen zum oemof Teil paper.
Mehr zu den Text Punkten im #88

**Comment by simnh** [comment]
thanks all!
