### ISSUE TITLE
Fix tables for els-class

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#84]
Tabellen müssen überarbeitet werden, da viel zu breit...ggf. hochkant? Fände ich aber nicht so schön.,,,
Wer kann das machen?

**Comment by gplssm** [comment]
Ich gehe das mal an...

Das review Format von Elsevier ist natürlich denkbar undankbar für etwas breitere Tabellen. Ich versuche es einigermaßen aussehen zu lassen. Wenn es im Notfall nur mit einer 90° gedrehten Variante geht, fände ich es nicht so schlimm, da das Format eh nur temporär ist. Nach dem Reviewprozess kommt der Artikel in das typische 2-spaltige Elsevier-Format...

**Comment by simnh** [comment]
super vielen Dank, ggf kann man bei der ersten tabelle auch die quellen rausschmeißen...aber das überlass ich dir!

**Comment by gplssm** [comment]
Ich habe das nun mit dem Paket tabularx gelöst. Dafür musste ich dieses extra einbinden. Ist aus meiner Sicht kein Problem (habe es auch bei anderen Elsevier-Publikationen verwendet).

Mit Tabelle 2 habe ich rumexperimentiert
- normal ausgerichtet im Text geht bei der Tabelle nicht, einfach zu schmal
- 90° gedrehte Tabelle, aber mit anderem Text auf der Seite, geht auch nicht siehe https://tex.stackexchange.com/questions/28085/sideways-table-placement-gets-deferred-more-than-expected

Also bekommt die Tabelle ihre eigene Seite. Ich halte das für unkritisch. 

Ich habe die Änderungen direkt in den Master gepusht.
