### ISSUE TITLE
Suggested Reviewers

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#86]
Also bei elsvier geht es nun mit vorschlagen, ich habe: 

tom brown, stefan pfenninger und mark howells ausgewählt, passt das so für alle ?

**Comment by fraukewiese** [comment]
find ich gut!

**Comment by gplssm** [comment]
Wobei mir der Gedanke kommt, dass wir das Paper auch noch ein bisschen challengen könnten, indem wir nicht 3 Reviewer aus der OpenMod vorschlagen. Was meint ihr?
