### ISSUE TITLE
Corresponding author is getting crazy: Divide paper in two

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#87]
Moin,

habe mit Cord geredet und wir sind uns einig, dass es besser ist das paper zwei zu teilen:

1) Framework (Beschreibung, Abgrenzung) (~4000 W) (IEEE, oder Energy Reports, ...)
2) Oemof Contribution (~6000- 7000W) (weiterhin Sus. and Renew Energy reviews)

Dafür habe ich ein neues repository angelegt mit der oemof beschreibung:

https://github.com/simnh/description_oemof

Dort fehlt nun der Abstract/Intro/Conclusion und ein bisschen Kapitel arrangieren, ggf. auffüttern. 

Außerdem einen branch angelegt im addressing repo divide/paper auf dem ich den oemof teil rausgeworfen habe. Ich habe dort schon fast alles angepasst und finde es viel besser so. Wir müssen nur noch das andere paper als quelle einfügen (sobald als preprint verfügbar), weil wir uns dann ja
auf dessen inhalt beziehen müssen. 

Kurzum: 

Ich denke in diesem repository können wir die todos (literatur etc) einfach abhaken und der aufwand ist sehr gering den rest anzupassen: 

* [ ] Quellen einfügen 
* [x] Abstract und introduction anpassen (habe ich schon gemacht, kann aber noch besser)

Folgende Vorteile: 

* 2 paper
* 1 paper on message 
* addressing kriegt einen besseren review charakter und passt damit besser be sus. rene. rev. rein
weil wir uns ja auf challenges literatur und oemof literatur beziehn (eine meta studie sozusagen) 
* Mach einfach mehr sinn...

**Comment by ckaldemeyer** [comment]
> Folgende Vorteile:
> 
> 2 paper
> 1 paper on message
> addressing kriegt einen besseren review charakter und passt damit besser be sus. rene. rev. rein
> weil wir uns ja auf challenges literatur und oemof literatur beziehn (eine meta studie sozusagen)
> Mach einfach mehr sinn...

* Die Wahrscheinlichkeit, dass die Paper durch den Review gehen ist m. E. um ein Vielfaches höher.
  * Bei Plos ONE ist es ja schon durch den Editor ("Passt das grundsätzlich in unser Journal?") abgelehnt worden und noch nicht einmal zum Reviewer ("Genügt es den Standards unseres Journals?") gekommen.
  * Für die "Teilpaper" gibt es in beiden Journals schon gleichartige Publikationen, auf die man sich beziehen kann bzw. an denen man sich orientieren kann
* Die Paper sind in sich "runder" und haben weniger Kanten bzw. werfen für Außenstehende weniger Fragen auf

**Comment by fraukewiese** [comment]
1) ich bin nicht überzeugt dass das besser ist
2) der teufel sitzt im abteil - äh detail (e.g. dann doch wieder unterschiedliche referenz, format anforderungen...)
3) das paper ist stimmig wie es ist, innerhalb des papers sind sehr viele gedanken die sich aufeinander beziehen, die wenn sie auseinandergerissen werden betreuung (=mehraufwand) bedeuten
4) ich halte euch für sehr fähig

aus all dem folgt, ich bin zwar nicht überzeugt, denke aber es wird wohl schon sinn dahinterstecken wenn euch das so wichtig ist es zu trennen. sicher bin ich aber dass der mehraufwand beträchtlich ist und beim wieder durchlesen getrennter paper und all den kleinen lang dauernden dingen am ende vorm einreichen wieder so viel zeit und arbeit drinsteckt.

daher: macht ma wenn ihr unbedingt wollt, ich warte dann erstmal irgendwas mit den referenzen zu machen @guido , wäre ja quatsch das zu erledigen bevor andere geklärt ist.

Bin halt nächste Woche bei openmod, danach hab ich 1,5 Wochen Urlaub, nur so zur Info Kapazitätenmäßig.

**Comment by gplssm** [comment]
Ich muss gestehen ich bin hin und her gerissen. Einerseits kann ich den Gedanken verstehen und bin der Überzeugung, dass man mit 2 Papern eine noch klarere Story bekommt. Auf der anderen Seite sehe ich wie Frauke den erheblichen Mehraufwand und weiß auch nicht wie gut wir ein rein oemof beschreibendes Paper platzieren können (mag aber meinem allg. Pessimismus geschuldet sein ;-)). Wir hatten uns damals ja bewusst entschieden das oemof Paper an dieser Story aufzuhängen.

Kurzum, für mich ist beides denkbar, allerdings zieht sich meine Promotion auch noch durch die nächsten Monate und lässt wenig Zeit für diese(s) Paper... Ich würde eigentlich gern mehr beitragen :( 
Also, wie Frauke eigentlich schon sagte. Wenn ihr eine starke Überzeugung habt zwei Paper daraus zu machen, go for it, aber meine praktische Unterstützung wird eher gering sein. Zumindest das zudem ich mich committen kann.

**Comment by ckaldemeyer** [comment]
> ich bin nicht überzeugt dass das besser ist
> der teufel sitzt im abteil - äh detail (e.g. dann doch wieder unterschiedliche referenz, format anforderungen...)
> das paper ist stimmig wie es ist, innerhalb des papers sind sehr viele gedanken die sich aufeinander beziehen, die wenn sie auseinandergerissen werden betreuung (=mehraufwand) bedeuten
> ich halte euch für sehr fähig
> aus all dem folgt, ich bin zwar nicht überzeugt, denke aber es wird wohl schon sinn dahinterstecken wenn euch das so wichtig ist es zu trennen. sicher bin ich aber dass der mehraufwand beträchtlich ist und beim wieder durchlesen getrennter paper und all den kleinen lang dauernden dingen am ende vorm einreichen wieder so viel zeit und arbeit drinsteckt.
> 
> daher: macht ma wenn ihr unbedingt wollt, ich warte dann erstmal irgendwas mit den referenzen zu machen @guido , wäre ja quatsch das zu erledigen bevor andere geklärt ist.
> 
> Bin halt nächste Woche bei openmod, danach hab ich 1,5 Wochen Urlaub, nur so zur Info Kapazitätenmäßig.

Ich würde sagen, dass wir am besten nochmal auf der openmod Konferenz darüber sprechen. Für mich überwiegen die Vorteile der 2 Paper Variante immer noch deutlich.

> Ich muss gestehen ich bin hin und her gerissen. Einerseits kann ich den Gedanken verstehen und bin der Überzeugung, dass man mit 2 Papern eine noch klarere Story bekommt. Auf der anderen Seite sehe ich wie Frauke den erheblichen Mehraufwand und weiß auch nicht wie gut wir ein rein oemof beschreibendes Paper platzieren können (mag aber meinem allg. Pessimismus geschuldet sein ;-)). Wir hatten uns damals ja bewusst entschieden das oemof Paper an dieser Story aufzuhängen.
> 
> Kurzum, für mich ist beides denkbar, allerdings zieht sich meine Promotion auch noch durch die nächsten Monate und lässt wenig Zeit für diese(s) Paper... Ich würde eigentlich gern mehr beitragen :(
> Also, wie Frauke eigentlich schon sagte. Wenn ihr eine starke Überzeugung habt zwei Paper daraus zu machen, go for it, aber meine praktische Unterstützung wird eher gering sein. Zumindest das zudem ich mich committen kann.

Wir posten dann hier das Update ;-)

**Comment by gplssm** [comment]
Ja, sprecht mal persönlich drüber, das ist dann vielleicht doch einfacher. Ich werde nicht beim Meeting dabei sein, aber ich vertraue drauf, dass ihr eine gute Entscheidung treffen werdet :)

**Comment by gplssm** [comment]
Any news?

**Comment by simnh** [comment]
sind immer noch der meinung das spitten mehr sinn macht...cord und ich wollen morgen und freitag das "oemof paper" fertig machen. dann bleiben nur noch kleine anpassungen bei dem anderen. aber wie gesagt die todos gelten ohnehin weiterhin (also literatur aufräumen etc)

**Comment by gplssm** [comment]
In anderen Worten ihr habt eine Entscheidung getroffen: 2 Paper. Richtig?
