### ISSUE TITLE
Finalize paper

### ISSUE THREAD

**Issue by simnh** [simnh/addressing_challenges_oemof#88]
Hi, 

wir haben jetzt das oemof paper feritg und ich habe die story line im anderen übrig gebliebenen teil angepasst. guckt euch das bitte mal an...

"features/divide-paper" heißt der branch oder so. Meiner meinung nach fehlt nur noch: 

* [ ] Methodology überarbeiten (habe das mal schnell hingedraftet) 
* [x]  sicherstellen, dass keine referenzen mehr zum vortext da sind, die nicht mehr vorhanden sind
* [x] Literatur einmal noch schick machen 
* [ ] Bib eintrag für das oemof paper hinzufügen...
* [x] Grundsätzliche Storyline des Papers überprüfen.

Für mich passt das aber so, ich finds gut. Denke nicht das noch mehr muss. Ich denke nocheinmal glatt zihen und dann ist gut.

**Comment by simnh** [comment]
Achso bitte nich mehr auf dem master oder so arbeiten!!!

**Comment by uvchik** [comment]
Bis einschließlich dem User-Meeting bin ich zeitlich am Limit. Danach kann ich mir gerne den Methodik-Teil nochmal angucken.

**Comment by ckaldemeyer** [comment]
> Bis einschließlich dem User-Meeting bin ich zeitlich am Limit. Danach kann ich mir gerne den Methodik-Teil nochmal angucken.

Geht mir genau so. Dann schaue ich aber auch nochmal drüber!

**Comment by fraukewiese** [comment]
Moinsen, bin zurueck.
Ist das oemof-paper schon eingereicht? Bei welchem Journal? Wo finde ich den aktuellen Stand?
Wo wird das oemof-paper eingereicht? Wie ist der Stand? Ist schon was passiert seitdem Simon das Issue eroeffnet hat?

**Comment by simnh** [comment]
zum 'oemof-only' paper: 
noch nicht eingereicht, vermutlich energy strategy reviews, paper ist fertig und wurde von Ilja gereviewt, wir arbeiten in kürze seine vorschläge ein, dann wird es eingereicht. du findest den aktuellen stand auf dem master branch hier: https://github.com/simnh/description_oemof

zu diesem addressing hier: es ist noch nicht passiert aber ich habe einen ersten Aufschlag gemacht. Die todos hier oben sind noch offen und können gerne bearbeitet werden

**Comment by fraukewiese** [comment]
hab gerade nochma alles gelesen vom addressing.
Danke Simon für die Arbeit. Kann nicht ganz einschätzen ob man es versteht wenn man gar keine Ahnung von oemof macht, bin aber dafür es nun trotzdem mit noch den unten angeregten einzureichen.
Meine ganzen Kommentare findet ihr im text-file comments_divided_paper_frauke, dass ich auch in diesen Branch gepusht hab. War auf meinem Arbeitsrechner und konnte nicht direkt im Dokument arbeiten. Aber der Übersicht halber fand ich es gar nicht so schlecht das nicht als pull-request zu machen.
Das meiste sind Rechtschriebdinge, ein paar Änderungen wegen oemof-Verweisen.
Größte (also kleinere größere) Punkte sind:
- Methodology nicht als Punkt 1.1 sondern als eigene Section
- am Anfang von Addressed challenges kurz erklären dass oemof framework ist und was es mit core components auf sich hat, sonst kommt es doch etwas seltsam
- Überschrift (- richtig geil wärs ja wenn die challenges trotzdem noch auftauchen / software würde ich rauslassen, weil es ja um mehr als software geht, evtl. durch tools ersetzen)
Entweder jemand schaut kurz rein und macht die Änderungen oder entscheidet dass sie nicht nötig sind, oder ich mach das Montag. Schreibt das einfach hier.

**Comment by simnh** [comment]
Cool, danke frauke. habe schonmal angefangen und die sachen die ich gemacht habe aus dem text file gelöscht. Die oemof quelle haben wir halt noch nicht, weil es ja das andere Paper ist...

Die ganzen rechtschreib etc sachen kannst du gerne machen. Das mit oemof am anfang etc. und dessen beschreibung sehe ich schon auch so. da sollte wir einen absatz habe der das andere paper zusammenfasst

**Comment by fraukewiese** [comment]
kann auch sehr kurz sein der absatz, aber vor allem dass es ein und was ein framework ist und das mit dem core components sollte kurz erkkärt werden. fast alles andere erschließt sich gut aus dem text.

Rechtschreib aus dem Textdokument mach ich Montag.

**Comment by fraukewiese** [comment]
Habe Tabellenformatierung, Rechtschreibung korriegiert. Nun sind nur noch ein paar Kommentare übrig im Textdokument "comments_divide_paper_frauke", die Du SImon @simnh DIr nochmal ansehen solltest, da ich da nicht nach meinem Gutdünken verändern wollte. Ist aber nicht mehr viel. Für die sehr kurze oemof Einführung damit man das adressing challenges versteht habe ich einen Vorschlag-Absatz gemacht im .tex Dokument als Kommentar.
Alles im divide/paper branch.
Wie geht es weiter?

**Comment by simnh** [comment]
Danke Frauke, den Vorschlag finde ich gut. Meiner Meinung ist dieser Absatz wichtig und sollte noch gemacht werden. Sonst ist es soweit...Ich werde mit Cord jetzt erstmal bis Ende dieser Woche den letzten Schliff für das oemof paper machen. und mich dann um den abschluss des anderen kümmern.
