### ISSUE TITLE
Artikelübersicht in Introduction

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#91]
Fehlende Artikelübersicht in Introduction. Muss abgestimmt sein mit quasi-Artikelüberblick am Ende von Ch. 2

**Comment by fraukewiese** [comment]
Da die Artikelübersicht am Ende Methodology gut war und geanu da hinpasst habe ich die Introduciton in Backgournd und Methodology geteilt und die Beschreibung so gelassen
