### ISSUE TITLE
Methodik mit Literatur belegen

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#92]
Die beschriebene Methodik mit anerkanntem Vorgehen einer qualitativen Analyse unterfütten, am besten mit Literaturreferenz. Ich bin da wirklich unbedarft auf dem Feld. Evtl. könnte es Richtung _Impact Analysis_ gehen. Falls ich Philipp Blechinger morgen sehe, spreche ich den mal drauf an... [hat bisher nicht geklappt]

**Comment by fraukewiese** [comment]
in der Einführung ein beispiel-paper  das sich quantitativ modelle anschaut und eines, das sich qualitativ modelle anschaut würde es schon machen, denk ich. für letzteres z.B. Conolly?
Die beschriebene Methodik ist doch ok, wir müssen kein theoretisches Gerüst hinter was aufbauen das wir gar nicht genutzt haben.

**Comment by simnh** [comment]
Ich denke auch das es nciht viel sein muss, Connolly finde ich u.a. einen guten Vorschlag. Das RegMex projekt könnte auch noch was sein. Fügt doch bitte hier hinzu falls euch noch was einfällt... ich würde das mal übernehmen,
