### ISSUE TITLE
Struktur der Diskussion in Kap. 4 entlang der beschriebenen Methodik

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#93]
Diskussion der adressierten Challenges (Kap.4) sollte dem in Methodik beschriebenen Vorgehen folgen. Dies ändert sich ggf. nochmal leicht in der Formulierung, allerdings steht dort recht deutlich, dass Argumente einzelner Charakteristiken  hinsichtlich der Relation zu einzelnen Askpekten der Challenges und deren Einfluss auf diese analysiert werden. Anhand "Complexity" (4.1) erkennt man, dass dies noch nicht so stringent verfolgt wird (historisch bedingt). Die anderen Sections 4.x gehen schon mehr in die Richtung.
Es sollten die Aspekte und Argumente noch mehr beim Namen genannt werden. Ich fände am Ende einer jeden Section einen zusammenfassenden Satz gut, der aussagt welche Askpete einer Challenge nur adressiert sind (und welche nicht). Dann kann sich der Leser meiner Meinung nach besser entlang hangeln.

Eine unterstützende Grafik (siehe #94 ) erleichtert das Verständnis m.E. noch mehr.

**Comment by fraukewiese** [comment]
Puuuh, das ist ne fette Aufgabe und ich bezweifel dass man dass ohne den Text zu zerstören und alles neu schreiben muss gut hinbekommt, daher würde ich dazu tendieren es zu lassen (Kosten-Nutzen-Abwägung...)

**Comment by simnh** [comment]
Ich gebe Frauke recht, würde mir das aber nochmal angucken wollen. Vorher fänd ich es gut, wenn @ckaldemeyer  nochmal drüber liest...
