### ISSUE TITLE
Arguments-Ascpects-Relationships Grafik

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#94]
Grafik plus/statt Tabelle 2: Es wäre prima wenn Tab. 2 um eine Grafik ergänzt wird, wo die Relation zwischen den einzelnen Argumenten und Aspekten mit ihrem jeweiligen Wert (+/o/-) angegeben wird. Gegebenenfalls kann die Tabelle auch ersetzt werden.

**Comment by fraukewiese** [comment]
Stimmt, das könnte sehr schick sein. Finde die Tabelle allerdings auch sehr gut, die gaukelt keine Genauigkeit vor, die es gar nicht so richtig gibt. Und die characteristics sind auch in Tabellenform. Denke so wie es ist ist es nicht zu fancy und verständlich. Geschmacksfrage ob ein Leser das ein oder andere besser findet. Daher wenn es viel Aufwand ist, ist die Tabelle auch sehr gut.

**Comment by ckaldemeyer** [comment]
Ich könnte mir ggf. Gedanken über eine Visualisierung machen, falls da noch keine Ideen bestehen

**Comment by ckaldemeyer** [comment]
Bzw. es sollte ja direkt aus der Tabelle hervorgehen ;)

**Comment by simnh** [comment]
> fände ich cool, ggf. geht halt auch beides...ich find deine vorschläge was visualisierung angeht immer sehr cool. von daher - gerne

fände ich cool, ggf. geht halt auch beides...ich find deine vorschläge was visualisierung angeht immer sehr cool. von daher - gerne

**Comment by ckaldemeyer** [comment]
Ich habe jetzt nur bis S.6 gelesen und den Rest überflogen aber bis dahin sind mir strukturell schon ein paar Dinge aufgefallen:

1.  Was genau ist der Aufhänger? Geht es primär um die entwickelte Methodik, die wir exemplarisch auf die derzeitigen Challenges und oemof mit seinen Eigenschaften anwenden? Oder geht es um die Challenges und wie oemof diese adressiert?

Ich hatte es eigentlich so verstanden, dass wir den ersten Weg (Methodik + Case Study) gehen. Dann würde ich der Methodik ein eigenes Kapitel widmen und diese allgemein (ohne Anwendung auf ein spezifisches Modell/Framework) vorstellung, die Einleitung um die entsprechenden Teile kürzen (Text verschieben) und die Methodik so optisch so in den Vordergrund rücken. Später ist oemof dann nur noch eine Case Study und in den Ergebnissen findet sich optimalerweise die vorne vorgestellte Methodik wieder.

2. Die erste Abbildung (Methodik) finde ich sehr gut.

3. Allgemein fände ich es passender den Begriff "Characteristic" durch "Property" zu ersetzen und den Begriff "Argument" durch "Characteristic (=Ausprägung)". Finde ich irgendwie klarer von der Sprache. Eine Challenge hat verschiedene Aspekte und eine Eigenschaft verschiedene Ausprägungen. Letztere adressieren dann die Aspekte einer Challenge..

Was meint ihr dazu?

4. Wenn es eine Tabelle mit Challenges gibt, sollte es m. E. auch eine mit Characteristics/Properties geben, da beides sehr wichtig für das Verständnis der Methodik ist und immer wieder auftaucht.

5. Die Tabelle mit dem Mapping der Challenges auf die Characteristics/Properties sollte um die Spalte "Aspects" erweitert werden, da man so alles im Blick hat und die Tabelle die Quintessenz des Papers darstellt.

6. Eine Abbildung, welche nur eine ausführliche Darstellung der "Mappingtabelle" darstellt könnte man z. B. mit einem Spinnennetzdiagramm finden.

Ich habe eben mal am Whiteboard versucht das ganze Paper (nur Tabellen und Abbildungen) für mich zu visualisieren. Hier mal ein Foto davon: https://pasteboard.co/fCSnN7EXo.jpg

Was meint ihr zu den o. g. Gedanken? Ein wenig Feedback wäre cool!

Solange lese ich schon mal weiter und fixe später Typos, Formulierungen, ...

**Comment by simnh** [comment]
Moin,

danke Cord für deinen analytischen Blick und das Feedback, klingt alles super!

zu 1) Also ich glaube nicht, dass wir soweit gehen könnnen zu behaupten, wir hätten eigene 'Methodik' entwickelt. Für mich wäre es so:

Es gibt Herausforderungen und Modelle müssen  evaluiert werden, dazu gibt es wenig (nichts?, vor allem qualitativ). Wir machen das jetzt mal und schlagen einen weg vor. Dazu nehmen wir unsere Methodik, die eben genau diese Evaluation anhand von Challenges vornimmt. Und das machen wir für oemof, weil das gerade mal neu und da ist als Beipiel anwendung (Naja jetzt wo ich so schreibe haben wir da vielleicht doch auch was entwickelt, zumindest einen Schritt in eine Richtung gemacht...daher auch der Titel so wie er ist). Es waren auch mal zwei getrennte Kapitel, finde ich auf jeden Fall gut (also Methodik in Vordergrund rücken).

zu 2) Danke

zu 3) Ja auf jeden, gerne! müssen wir nur stringent hinkriegen

zu 4,5,6) jo zwei tabellen, die auf die Ergebnisse bzw. Zwischeergebnisse (z.B. gruppierte Challenges) darstellen find ich richtig. Ist ja auch so, kann halt noch verbessert und stärker an die Methodik angelehnt werden. Spinne find ich auch gut, Ich glaube so eine Grafik sollten wir mit reinem..Visualisierung macht einfach Sinnund ich denke nicht, dass es dann doppelt wäre.

Geile Sache das mit dem Whiteboard, ich finde so wird ein Schuh draus! Immer gut dich an Board zu haben!!!!

Diese Woche habe ich so gut wie keine Zeit mehr vielleicht noch Freitag im Zug, aber nächste Woche würde ich mir möglichst viel davon nehmen!

Bis dann!


________________________________

**Comment by ckaldemeyer** [comment]
> Moin,
> 
> danke Cord für deinen analytischen Blick und das Feedback, klingt alles super!
> 
> zu 1) Also ich glaube nicht, dass wir soweit gehen könnnen zu behaupten, wir hätten eigene 'Methodik' entwickelt. Für mich wäre es so:
> 
> Es gibt Herausforderungen und Modelle müssen  evaluiert werden, dazu gibt es wenig (nichts?, vor allem qualitativ). Wir machen das jetzt mal und schlagen einen weg vor. Dazu nehmen wir unsere Methodik, die eben genau diese Evaluation anhand von Challenges vornimmt. Und das machen wir für oemof, weil das gerade mal neu und da ist als Beipiel anwendung (Naja jetzt wo ich so schreibe haben wir da vielleicht doch auch was entwickelt, zumindest einen Schritt in eine Richtung gemacht...daher auch der Titel so wie er ist). Es waren auch mal zwei getrennte Kapitel, finde ich auf jeden Fall gut (also Methodik in Vordergrund rücken).

Vielleicht wäre das echt zu dick aufgetragen mit ner entwickelten Methodik. Aber so wie im Titel a la "A step towards evaluation" wäre das m. E. echt in Ordnung. Ich habe so etwas zumindest noch nicht gesehen..



> zu 2) Danke
> 
> zu 3) Ja auf jeden, gerne! müssen wir nur stringent hinkriegen
> 
> zu 4,5,6) jo zwei tabellen, die auf die Ergebnisse bzw. Zwischeergebnisse (z.B. gruppierte Challenges) darstellen find ich richtig. Ist ja auch so, kann halt noch verbessert und stärker an die Methodik angelehnt werden. Spinne find ich auch gut, Ich glaube so eine Grafik sollten wir mit reinem..Visualisierung macht einfach Sinnund ich denke nicht, dass es dann doppelt wäre.
> 
> Geile Sache das mit dem Whiteboard, ich finde so wird ein Schuh draus! Immer gut dich an Board zu haben!!!!
> 
> Diese Woche habe ich so gut wie keine Zeit mehr vielleicht noch Freitag im Zug, aber nächste Woche würde ich mir möglichst viel davon nehmen!
> 
> Bis dann!

Danke. Alles klar, ich mache dann einfach mal weiter. Wobei es heute wohl nix mehr wird mit dem pushen. Aber dann morgen..

Grüße

**Comment by ckaldemeyer** [comment]
Vielleicht ist ein modifizierter Multilevel-Piechart noch schöner: https://en.wikipedia.org/wiki/Pie_chart#/media/File:Disk_usage_(Boabab).png

Aber ich nehme erstmal die anderen Änderungen vor..

**Comment by ckaldemeyer** [comment]
Oder sowas hier: http://matplotlib.org/examples/pie_and_polar_charts/polar_bar_demo.html

**Comment by ckaldemeyer** [comment]
Die Farben könnten dann auf die Properties gemappt werden..

**Comment by ckaldemeyer** [comment]
https://github.com/simnh/addressing_challenges_oemof/pull/98

**Comment by ckaldemeyer** [comment]
Das ist der PR. Ich melde mich wenn ich damit durch bin..

**Comment by ckaldemeyer** [comment]
Hier ist die neue Abbildung zur Methodik: https://pasteboard.co/gq8HKIxsV.png

Wäre es eine Idee die Arguments-Ascpects-Relationships Abbildung einfach in dem Stil unter (3.) anzufertigen, also einfach mit Boxen und Pfeilen? Hätte den Vorteil, dass es schnell geht und im gleichen Stil wäre die Methodikt- und Evaluationsabbildung wäre. Ein Nachteil wäre, dass es ggf. eine größere Abbildung wird. Fände ich aber vertretbar. Ist ja auch die Quitessenz des (recht langen) Papers..

**Comment by simnh** [comment]
find ich nicht so schlimm, man könnte sie natürlich teilen und den beschreiben text drum rum wrappen...

**Comment by simnh** [comment]
ich würde um 12:30 nochmal pull und dann ins mdpi teplate übertragen. cool ist, dass energies und sustainablitiy dasselbe template haben...

**Comment by ckaldemeyer** [comment]
> find ich nicht so schlimm, man könnte sie natürlich teilen und den beschreiben text drum rum wrappen...

das ginge schon aber ich finde eine zentrale abbildung, in der man alle ergebnisse findet, echt schick. aber wenn man auf maximal eine seite geht, klappt das ja problemlos. fände ich nicht schlimm. rumspielen kann man ja später immer noch. und im prinzip visualisiert das nur die tabelle.

1. Tabelle um Spalte "Aspects" erweitern
2. Zentrale Abbildung entweder/oder
    1. Nur Mapping von Properties auf Challenges (komprimierte Form)
    2. 1:1-Abbildung der Tabelle, d. h. Mapping mit Pfeilen zwischen Characteristics und Aspects

so stellt es sich gerade in meinem kopf dar und ich finde beides o.k. bzw. argumentierbar.

**Comment by ckaldemeyer** [comment]
> ich würde um 12:30 nochmal pull und dann ins mdpi teplate übertragen.

ich pushe um 12.26 ;-)

> cool ist, dass energies und sustainablitiy dasselbe template haben...

:+1:

**Comment by ckaldemeyer** [comment]
> ich würde um 12:30 nochmal pull und dann ins mdpi teplate übertragen.
> ich pushe um 12.26 ;-)

done. schönes wochenende!
