### ISSUE TITLE
Verwendung Begriff "aspects"

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#95]
Sicherstellen, dass der Term "aspects" in Kapitel 3 geprägt und anschließend durchgehend verwendet wird

**Comment by fraukewiese** [comment]
aspects teilweise von anderem wording geändert, teilweise hinzugefügt wenn es genau der Begriff aus der Tabelle war in Kapitel 2 was vorher Kapitel 3 war
