### ISSUE TITLE
Überarbeitung Absatz zu Einführung oemof

### ISSUE THREAD

**Issue by gplssm** [simnh/addressing_challenges_oemof#97]
Siehe Mail von Simon.

@gplssm: Änderungsvorschläge aus schriftl. Aufzeichnungen einfügen.

**Comment by fraukewiese** [comment]
??? versteh ich nicht, ist das nicht schon erledigt?

**Comment by simnh** [comment]
Ich denke, es kann nocheinmal auf Übereinstimmung mit dem anderen Paper einerseits und auf die Contribuition andereseits gegengecheckt werden. D.h alle notwendingen oemof aspekte sollten kurz genannt sein (nicht ausführlich erläutert), wenn sie in der bewertung von oemof eine Rolle spielen...

@ckaldemeyer : Bock drauf?

**Comment by ckaldemeyer** [comment]
> Ich denke, es kann nocheinmal auf Übereinstimmung mit dem anderen Paper einerseits und auf die Contribuition andereseits gegengecheckt werden. D.h alle notwendingen oemof aspekte sollten kurz genannt sein (nicht ausführlich erläutert), wenn sie in der bewertung von oemof eine Rolle spielen...
> 
> @ckaldemeyer : Bock drauf?

Kann ich übernehmen.

**Comment by gplssm** [comment]
Simon hat das schon ganz gut erfasst. Ich habe auf dem ausgedruckten Exemplar noch ein paar Gedanken dazu. Könnte sie aber erst nach dem Urlaub beisteuern.

**Comment by simnh** [comment]
Ich denke der Absatz könnte noch etwas ausführlicher sein...
