### ISSUE TITLE
Journalwahl die Fünfte..

### ISSUE THREAD

**Issue by ckaldemeyer** [simnh/addressing_challenges_oemof#99]
Weil die Fördermittel ja leider nicht für hybride Journals zur Verfügung stehen, hier mal zwei Vorschläge für Journals aus dem [Directory of Open Access Journals (DOAJ)](https://doaj.org/), die auf jeden Fall in die Förderung fallen:

* Journal of Modern Power Systems and Clean Energy (IF=0.975): http://www.springer.com/energy/systems%2C+storage+and+harvesting/journal/40565
* Sustainability (IF: 1.343): http://www.mdpi.com/journal/sustainability

Ich fände Sustainability ganz passend..

**Comment by ckaldemeyer** [comment]
Vom Hörensagen weiß ich, dass es beim ersten Journal teilweise sehr lange dauern soll. Zudem ist es thematisch etwas technischer..

**Comment by simnh** [comment]
klingt gut...

**Comment by ckaldemeyer** [comment]
> klingt gut...

Wenn die anderen einverstanden sind, könnten wir schon die Mittel beantragen. Würde wegen der Topfgröße über die EUF gehen. Entweder du machst das (Nummer sicher) oder ich als EUF Promotionsstudent. Sollte ja auch kein Problem sein..

**Comment by simnh** [comment]
kannst du den antrag kurz drucken ?dann komm ich gleich in der pause hoch und füll den aus..

**Comment by ckaldemeyer** [comment]
> kannst du den antrag kurz drucken ?dann komm ich gleich in der pause hoch und füll den aus..

jo

**Comment by ckaldemeyer** [comment]
Mist, ein Journal hatte ich noch vergessen!

* Energies (IF:  2.468): http://www.mdpi.com/journal/energies

Nochmal ändern auf dem Antrag? Ginge ja fix mit Tippex..

**Comment by ckaldemeyer** [comment]
Ich glaube das ist aber schon nicht ohne. Das muss schon tiptop sein. Wird es ja aber auch ;)

**Comment by simnh** [comment]
mh...naja wenn wir das eine blockt haben, können wir es sicher auch ändern...aber ich denke sustainability ist irgendwie besser geeignet, weil energies doch sehr technisch orientiert ist

**Comment by ckaldemeyer** [comment]
> mh...naja wenn wir das eine blockt haben, können wir es sicher auch ändern...aber ich denke sustainability ist irgendwie besser geeignet, weil energies doch sehr technisch orientiert ist

Mir latte. Dann lassen wir es so!
